### PR TITLE
Fix issues with mpi_assert_allow_overtaking

### LINKED ISSUE #9846: Inconsistent setting of mpi_assert_allow_overtaking leads to deadlock
This is a dedicated issue for a problem reported in https://github.com/open-mpi/ompi/pull/9843. The fix there likely isn't what we want so I create a separate issue.

Setting the `mpi_assert_allow_overtaking` info key can happen in a way that creates inconsistencies between MPI processes. Processes with different `mpi_assert_allow_overtaking` info values exchanging messages will cause errors or deadlock. 

Here is a minimal reproducer for the problem:

```C
#include <unistd.h>
#include <mpi.h>

int main(int argc, char **argv)
{
  int rank, value;
  MPI_Init(&argc, &argv);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);

  MPI_Comm comm;

  MPI_Comm_dup(MPI_COMM_WORLD, &comm);

  MPI_Info no_order;
  MPI_Info_create(&no_order);
  MPI_Info_set(no_order, "mpi_assert_allow_overtaking", "true");

  if (rank == 0) {
    MPI_Send(&value, 1, MPI_INT, 1, 100, comm);
    MPI_Comm_set_info(comm, no_order);
    MPI_Send(&value, 1, MPI_INT, 1, 100, comm);
  } else {
    sleep(5); // increase the window of opportunity
    MPI_Recv(&value, 1, MPI_INT, 0, 100, comm, MPI_STATUS_IGNORE);
    MPI_Comm_set_info(comm, no_order);
    MPI_Recv(&value, 1, MPI_INT, 0, 100, comm, MPI_STATUS_IGNORE);
  }

  MPI_Info_free(&no_order);
  MPI_Finalize();
  return 0;
}
```

Process 1 will hang in the second receive because the second message will be encountered before the info key is set (thanks to eager sending). Based on a discussion with @bosilca, my understanding is that the second message is put into a queue from which it is not taken after the info key is set (I'm on very thin ice when it comes to ob1, sorry). Everything runs fine without the info key.

@bosilca and I came up with three possible fixes:

1) The one proposed in https://github.com/open-mpi/ompi/pull/9843: guard ensuing communication before/after setting the info key with barriers. This is costly and there is a chance that it is breaking existing codes (MPI says that `MPI_Comm_set_info` is collective but no implementation is synchronizing, according to @bwbarrett). Plus, there might still be an opportunity to break the second barrier if one of its messages encounters an inconsistency between sender and receiver (unless we also exclude collective internal p2p from using allow-overtake in ob1, as proposed in #9843). 
2) Disallow dynamically setting `mpi_assert_allow_overtaking` in `MPI_Comm_set_info` and only support it in communicator creation/duplication. That will be safe and an easy fix, but there may be applications that rely on the support for dynamic setting. Info keys can be ignored at any time.
3) Fix ob1 to properly manage the case where the info value is set dynamically (draining the queue of messages that could not yet be matched, from what I understand). I don't know enough about ob1 to know whether this is viable.

### PR DESCRIPTION
**Pull request by devreal**
This PR addresses two problems with the `mpi_assert_allow_overtaking` info key:

1) The ob1 PML handles the `mpi_assert_allow_overtaking` key, which then also would apply to internal p2p communication of collective operations. The collective operations should not be affected, so we need to check whether the provided tag belongs to a collective operation.
2) Setting the info key can happen in a way that creates inconsistencies between MPI processes. Processes with different `mpi_assert_allow_overtaking` info values exchanging messages will cause errors or deadlock. MPI says that `MPI_Comm_set_info` is collective, so make it so by protecting both previous and subsequent communication from inconsistencies by using barriers. This is expensive but setting info keys should not occur in performance critical parts of an application (hopefully).

This needs to be backported to 5.0.x.

Fixes #9846 

Signed-off-by: Joseph Schuchart <schuchart@icl.utk.edu>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/fbd0f15518c24875e17c5e7e4cbe2cd1

File: ompi/mpi/c/comm_set_info.c [hunk 1]
```diff
@@ -46,7 +46,13 @@ int MPI_Comm_set_info(MPI_Comm comm, MPI_Info info)
         }
     }
 
+    /* protect communication posted earlier from inconsistent info states */
+    comm->c_coll->coll_barrier (comm, comm->c_coll->coll_barrier_module );
```
Comment (bwbarrett) [inline ompi/mpi/c/comm_set_info.c:50]: I have concern about this change.  I agree that the standard allows for it, but I'm not aware of any MPI implementation that actually enforces the collective nature of MPI_Comm_set_info.  There's a FIXME note in MPICH that they should, to ensure consistency, but no actual enforcement.  We have no idea what codes we'd break by adding this code.  Given how long we've shipped the allow_overtaking flag, I'm not sure I have a great solution to this problem.

If we are going to risk breaking codes, shouldn't we also switch from a barrier to some form of consistency checking check?

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/6e04812e5f5c5b6d3d4a455a313db1fe

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/d99268b1e23f0970ccbaca4151fc56ad

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/1891845e3d418804bafc842ae7e27f66

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by devreal** [comment]
I think @bosilca has found a solution to the dynamic setting of the allow-overtake info key: allow setting it once and then ignore any further attempts to change it (see the comment here https://github.com/open-mpi/ompi/pull/9843/files#diff-cd338aa28467c267935a0b882b90291a86b071af01c742ac2bfeb97f8493c224R225). We also discussed the issue of excluding collective operation messages and came down to excluding all internal messages. User info key settings should not affect internal communication. In the future, we might want to allow components to flag individual messages as allowed to be unordered (may be used by some collectives) independent of the allow-overtake info key.

The barriers from comm_setinfo were removed since they are not needed anymore.

@bwbarrett could you take a look at this PR again?

**Review by bosilca — APPROVED** [review]

File: ompi/mca/pml/ob1/pml_ob1.c [hunk 2]
```diff
@@ -202,6 +202,44 @@ int mca_pml_ob1_enable(bool enable)
...
+         * overtake, before any potential sender start sending valid sequence numbers there
+         * is no way to order the messages in a sensible order.
+         * The possible solution is cumbersome, it would force a network quiescence followed by
+         * a synchronization of all processes in the communicator, and then all peers will
+         * start sending messages starting with sequence number 0.
+         * A lot of code for minimal benefit, especially taking in account that the MPI standard
+         * does not define this. Instead, refuse to disable allow overtake, and at least the
+         * user has the opportunity to check if we accepted to change it.
+         */
+        opal_output(0, "Cannot change the mpi_allow_overtake to false while after the communicator creation.\n");
```
Comment (bwbarrett) [inline ompi/mca/pml/ob1/pml_ob1.c:237]: This should go to stderr, not stdout.  However, I'm not convinced we should print here at all.  This is not an error condition, and we know some applications behave poorly in the face of output on stdout/stderr during normal operation.  Perhaps a verbose print?  I don't know; there's no good here.  But at a minimum, let's print to stderr.

**Review by bwbarrett — CHANGES_REQUESTED** [review]

File: ompi/mca/pml/ob1/pml_ob1.c (hunk 2 above)
Comment (bosilca) [reply ompi/mca/pml/ob1/pml_ob1.c]: MPI can ignore an assertion, so a message is not really necessary as users are supposed to check if their assertions were accepted by the library.

**Comment by devreal** [comment]
@bwbarrett Can you please rereview?

**Review by bwbarrett — APPROVED** [review]
