### PR TITLE
Don't overwrite NULL descriptors.

### LINKED ISSUE #10031: SEGFAULT in ompi/opal/mca/btl/smcuda/btl_smcuda.c at *descriptor = NULL
## Background information

OpenMPI versions: 3.0.0, 4.1.0, 4.1.2

All of them installed from source via:
./configure --with-cuda=/usr/local/cuda --prefix=/usr/local/openmpi-<major>.<minor>.<patch>/

Was tested on Ubuntu20.04 and CentOS7 with NVIDIA GTX 1080Ti and NVIDIA RTX 2080 with CUDA 11.0, 11.2, 11.3 and 11.4.

-----------------------------

## Details of the problem

The problem happens when sending asynch. a high number of small message (765 per GPU on 6 processes (6 GPUs)) via ISend + IRecv from global memory on GPU.
I compiled OpenMPI in debug mode via CPPFLAGS=-DDEBUG CFLAGS="-g -O0" and got this backtrace
https://pastebin.com/a7K8jGfF

It seems the issue happens because in ompi/opal/mca/btl/smcuda/btl_smcuda.c at *descriptor = NULL

        /* allocate a fragment, giving up if we can't get one */
        /* note that frag==NULL is equivalent to rc returning an error code */
        MCA_BTL_SMCUDA_FRAG_ALLOC_EAGER(frag);
        if (OPAL_UNLIKELY(NULL == frag)) {
            *descriptor = NULL;
            return OPAL_ERR_OUT_OF_RESOURCE;
        }
        
where descriptor is a NULLPTR but still is dereferenced.
(gdb) print descriptor
$1 = (mca_btl_base_descriptor_t **) 0x0
(gdb) print *descriptor
Cannot access memory at address 0x0

This creates a fatal crash with SIGSEGV without any info of the real issue, which makes it difficult to find what causes it.

Edit: Following the backtrace it seems it will always be a NULLPTR here

    /* try to send immediately */
    rc = mca_bml_base_sendi (bml_btl, &convertor, &match, OMPI_PML_OB1_MATCH_HDR_LEN,
                             size, MCA_BTL_NO_ORDER, MCA_BTL_DES_FLAGS_PRIORITY | MCA_BTL_DES_FLAGS_BTL_OWNERSHIP,
                             MCA_PML_OB1_HDR_TYPE_MATCH, NULL);

### PR DESCRIPTION
**Pull request by bosilca**
If the descriptor is NULL in sendi don't try to provide back a fragment.

Fixes #10031.

### CODE REVIEW

File: opal/mca/btl/smcuda/btl_smcuda.c [hunk 1]
```diff
@@ -887,8 +887,7 @@ int mca_btl_smcuda_sendi(struct mca_btl_base_module_t *btl,
         /* note that frag==NULL is equivalent to rc returning an error code */
         MCA_BTL_SMCUDA_FRAG_ALLOC_EAGER(frag);
         if (OPAL_UNLIKELY(NULL == frag)) {
-            *descriptor = NULL;
-            return OPAL_ERR_OUT_OF_RESOURCE;
+            goto return_resource_busy;
```
Comment (jsquyres) [inline opal/mca/btl/smcuda/btl_smcuda.c:890]: Is it ok that this now returns `RESOURCE_BUSY` instead of `OUT_OF_RESOURCE`?

Comment (bosilca) [reply opal/mca/btl/smcuda/btl_smcuda.c:890]: Any return code has the same meaning, aka. no side effect and the upper layer needs to find another route to send the data.

**Review by jsquyres — APPROVED** [review]
