### PR TITLE
Fix mpirun --timeout orphan issue

### LINKED ISSUE #9369: Orphaned processes on launch node when --timeout is triggered
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

`v4.0.x` [HEAD](https://github.com/open-mpi/ompi/commit/14cc1897834a8c17ddcb949e7d8ddf4bdf54e968) and `v4.1.x` [HEAD](https://github.com/open-mpi/ompi/commit/02d6331a138db9e35e8e8fa5f76d9c231869f1c6) branches are impacted.

`v5.0.x` and `master` are not impacted.

Related tickets:
 * PR #9272
 * PR #9350

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Installed from git clone on ppc64le system with GNU compiler.

### Please describe the system on which you are running

* Operating system/version: RHEL 7.7
* Computer hardware: ppc64le
* Network type: Ethernet (`tcp,vader,self`)

-----------------------------

## Details of the problem

Using the `--timeout` option to `mpirun` will result in orphaned processes on the same node as `mpirun` if the timeout is triggered. The processes on the remote node were cleaned up correctly.

Originally we thought this was limited to non-MPI applications since the MPI application were terminating correctly. However, while root causing this issue we were able to determine that MPI applications are impacted, but are getting terminated differently when the PMIx connection drops.

Experimental setup:
 * 2 nodes - 2 processes per node
 * `mpirun --map-by ppr:2:node --host f7n01:2,f7n02:2 --timeout 2 <APP>`
 * Three applications used:
   1. `sleep 30` : System utility - Non-MPI application
   1. `hello_c` : C application that calls `sleep(30)` before exiting
   1. `hello_mpi` : C application that does an `MPI_Init` followed by `sleep(30)` followed by `MPI_Finalize`
 * Watched the system processes on both nodes to monitor if orphans were generated.

Running the following will orphan the processes on the `mpirun` node after `mpirun` completes.
```
mpirun --map-by ppr:2:node --host f7n01:2,f7n02:2 --timeout 2 sleep 30
mpirun --map-by ppr:2:node --host f7n01:2,f7n02:2 --timeout 2 hello_c
```

Running the following will not orphan the process:
```
mpirun --map-by ppr:2:node --host f7n01:2,f7n02:2 --timeout 2 hello_mpi
```

-----------------------------

## Root cause analysis

I attached to the `mpirun` process after application launch, but before the timeout was triggered. In all three cases (including the MPI case) `mpirun` was idling in the first loop in [this section of code](https://github.com/open-mpi/ompi/blob/02d6331a138db9e35e8e8fa5f76d9c231869f1c6/orte/tools/orterun/orterun.c#L176-L197) - waiting for the launch to complete, not waiting for the job to complete (second loop):
```
    // wait for response and unpack the status, jobid
    while (orte_event_base_active && launchst.active) {
        opal_event_loop(orte_event_base, OPAL_EVLOOP_ONCE);
    }
    ORTE_ACQUIRE_OBJECT(orte_event_base_active);
    if (orte_debug_flag) {
        opal_output(0, "Job %s has launched",
                   (NULL == launchst.jdata) ? "UNKNOWN" : ORTE_JOBID_PRINT(launchst.jdata->jobid));
    }
    if (!orte_event_base_active || ORTE_SUCCESS != launchst.status) {
        goto DONE;
    }


    while (orte_event_base_active && completest.active) {
        opal_event_loop(orte_event_base, OPAL_EVLOOP_ONCE);
    }
    ORTE_ACQUIRE_OBJECT(orte_event_base_active);


    if (ORTE_PROC_IS_HNP) {
        /* ensure all local procs are dead */
        orte_odls.kill_local_procs(NULL);
    }
```

At a high level, `mpirun` is waiting for the job launch to complete instead of moving on to the loop where it waits for the job to complete. I confirmed that the job launched successfully, and `mpirun` is aware of that since the job state `ORTE_JOB_STATE_RUNNING` was activated and [the associated](https://github.com/open-mpi/ompi/blob/02d6331a138db9e35e8e8fa5f76d9c231869f1c6/orte/mca/state/hnp/state_hnp.c#L87-L109) `orte_plm_base_post_launch` function was called. The problem was that that information was not propagated to the `mpirun` process so that it would move on to the next loop.

 * When the timeout is triggered the `orte_timeout_wakeup()` function is called which sets the state of [`ORTE_JOB_STATE_ALL_JOBS_COMPLETE `](https://github.com/open-mpi/ompi/blob/02d6331a138db9e35e8e8fa5f76d9c231869f1c6/orte/orted/orted_submit.c#L3228-L3231)
 * This actives the `orte_quit` functions from the [`state/hnp` component](https://github.com/open-mpi/ompi/blob/02d6331a138db9e35e8e8fa5f76d9c231869f1c6/orte/mca/state/hnp/state_hnp.c#L93-L114)
 * `orte_quit` will [break the event loop](https://github.com/open-mpi/ompi/blob/02d6331a138db9e35e8e8fa5f76d9c231869f1c6/orte/runtime/orte_quit.c#L140-L143)
 * This will cause `mpirun` to leave the first loop in the code section above and enter the `goto DONE` statement from the ` if (!orte_event_base_active || ORTE_SUCCESS != launchst.status) {` check
    - launchst.active = true
    - launchst.status = 0
    - orte_event_base_active = false
 * `mpirun` then jumps into the shutdown skipping over the `orte_odls.kill_local_procs(NULL);` thus orphaning local processes.
   * Why are MPI applications not orphaned? Because in `orte_finalize` we call `opal_pmix.server_finalize` (`PMIx_server_finalize`) which will eventually call `pmix_ptl_base_stop_listening` to drop the socket between the `mpirun` process and each local application process. The local (PMIx enabled) application processes will see the socket drop and shutdown. Without this mechanism we would have seen the MPI processes also be orphaned by `mpirun`.

-----------------------------

## Solution summary

The core problem is that `mpirun` is not transitioning to the "waiting for completion" after a successful launch.
To resolve this problem we need a call from `orte_plm_base_post_launch` (triggered when the job enters the state `ORTE_JOB_STATE_RUNNING`) to the `mpirun` process to tell it to move to the next phase.

There is a potential secondary problem where if the local launch is successful, but the remote launch fails then local orphans could still be generated since the `mpirun` process will then skip over the code to terminate the local processes.
Upon investigation, the `errmgr/default_hnp` component is actived in this state and end up in [this call](https://github.com/open-mpi/ompi/blob/02d6331a138db9e35e8e8fa5f76d9c231869f1c6/orte/mca/errmgr/default_hnp/errmgr_default_hnp.c#L858-L860) to `orte_plm.terminate_orteds`. This will eventually trigger `mpirun` to terminate the local processes.

We could add the code to `orte_odls.kill_local_procs(NULL);` if the launching loop fails in an abundance of caution, but it is not 100% necessary it seems.

### PR DESCRIPTION
**Pull request by jjhursey**
* Fixes #9369
 * `mpirun` was idling waiting for the launch to complete because its
   tracker was never triggered once the launch was complete. This caused
   `mpirun` to skip over the code to terminate local children (since it
   assumes that it had a failed launch and the errmgr did that) thus
   orphaning the local children.
   -  This fix activates the tracker in the `mpirun` process causing it
      to correctly move to the waiting for completion state.
 * If the remote daemon is slow launching and the timeout triggers before
   the launch is complete then the `mpirun` process will orphan the local
   processes.
   - This fix will have the `mpirun` process try to kill the local processes
     in this case.
 * Only impacts the `v4.0.x` and `v4.1.x` branches
    
bot:notacherrypick

### CODE REVIEW

**Comment by jjhursey** [comment]
One more fix coming... I found a corner case that needs plugged.

**Comment by jjhursey** [comment]
Ok just re-pushed with the secondary fix.

**Review by gpaulsen — APPROVED** [review]
Josh did a nice desk-review with @awlauria @dsolt and I and walked us through the various code paths (mpi, vs non-mpi), Tool-attach mode, when using `--timeout`.  He's done a good job describing this in the issue for others to follow as well.

File: orte/mca/plm/base/plm_base_launch_support.c [hunk 1]
```diff
@@ -700,6 +701,9 @@ void orte_plm_base_post_launch(int fd, short args, void *cbdata)
                              "%s plm:base:launch job %s is not a dynamic spawn",
                              ORTE_NAME_PRINT(ORTE_PROC_MY_NAME),
                              ORTE_JOBID_PRINT(jdata->jobid)));
+        if (ORTE_PROC_IS_HNP) {
+            orte_submit_job_state_update(jdata, ORTE_JOB_STATE_RUNNING);
```
Comment (awlauria) [inline orte/mca/plm/base/plm_base_launch_support.c:705]: The return code here is ignored, should anything be done (or make it a void)?

File: orte/orted/orted_submit.c [hunk 2]
```diff
@@ -3363,3 +3363,26 @@ void orte_profile_wakeup(int sd, short args, void *cbdata)
...
+        if ( !orte_get_attribute(&jdata->attributes, ORTE_JOB_ROOM_NUM, (void**)&rmptr, OPAL_INT)) {
+            opal_output(0, "Error: ORTE_JOB_ROOM_NUM not a valid attribute for this job");
+            return ORTE_ERROR;
+        }
+        if (NULL == (trk = (trackr_t*)opal_pointer_array_get_item(&tool_jobs, room))) {
+            opal_output(0, "Error: Tracker ID %d returned a NULL object", room);
+            return ORTE_ERROR;
+        }
+        if (NULL != trk->launch_cb) {
+            trk->launch_cb(room, trk->jdata, ORTE_SUCCESS, trk->launch_cbdata);
```
Comment (awlauria) [inline orte/orted/orted_submit.c:3383]: Does this return an rc that should be checked?

File: orte/orted/orted_submit.c [hunk 3]
```diff
@@ -3363,3 +3363,26 @@ void orte_profile_wakeup(int sd, short args, void *cbdata)
     /* abort the job */
     ORTE_ACTIVATE_JOB_STATE(NULL, ORTE_JOB_STATE_ALL_JOBS_COMPLETE);
 }
+
+int orte_submit_job_state_update(orte_job_t *jdata, orte_job_state_t state)
```
Comment (awlauria) [inline orte/orted/orted_submit.c:3367]: nit: instead of passing in state, it could be checked at a higher level. It's fine as is though.

**Review by awlauria — APPROVED** [review]
I like it, great digging. Just some minor comments. Thanks!

**Comment by rhc54** [comment]
There are differences, but I wonder if some similar issue exists in PRRTE?

@jjhursey Can you test OMPI master with what you did here?

File: orte/mca/plm/base/plm_base_launch_support.c (hunk 1 above)
Comment (jjhursey) [reply orte/mca/plm/base/plm_base_launch_support.c:705]: Nothing to be done here. I'd keep it `int` for now just in case we need to do something in the future.

File: orte/orted/orted_submit.c (hunk 2 above)
Comment (jjhursey) [reply orte/orted/orted_submit.c:3383]: I can add the check to be consistent with the rest of this function.

Comment (jjhursey) [reply orte/orted/orted_submit.c:3383]: Actually I take that back the `orte_submit_cbfunc_t` returns `void` so there is nothing to check here.

File: orte/orted/orted_submit.c (hunk 3 above)
Comment (jjhursey) [reply orte/orted/orted_submit.c:3367]: Yeah I put in the state here because there is also a 'completing' callback that we could wire in. I didn't go that far in this PR since it wasn't needed for the bug fix and the side effects of that were unknown. I kept the function like this in case we need to wire it back in later - we can do so without adding a new function.

**Comment by jjhursey** [comment]
I ran against both master and `v.5.0.x` and did not see the problem, but I didn't look much further than that. Let me take a quick look at PRTE to see.

**Comment by awlauria** [comment]
bot:aws:retest

java failure
