### PR TITLE
Use #ifdef with system headers

### LINKED ISSUE #13647: Missing config test for ucred.h
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)

Current head of OMPI main

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Git clone

### Please describe the system on which you are running

* Operating system/version: Rocky 9
* Computer hardware: container
* Network type: TCP

-----------------------------

## Details of the problem

Building normally and hit the following warning/error:
```
btl_tcp_component.c:62:5: warning: "HAVE_SYS_UCRED_H" is not defined, evaluates to 0 [-Wundef]
   62 | #if HAVE_SYS_UCRED_H
```
Apparently, OMPI is missing the check for sys/ucred.h in its configure logic

### PR DESCRIPTION
**Pull request by bosilca**
Fixes #13647

### CODE REVIEW

File: opal/mca/btl/tcp/btl_tcp_component.c [hunk 1]
```diff
@@ -59,7 +59,7 @@
 #ifdef HAVE_SYS_TIME_H
 #    include <sys/time.h>
 #endif
-#if HAVE_SYS_UCRED_H
+#ifdef HAVE_SYS_UCRED_H
```
Comment (jsquyres) [inline opal/mca/btl/tcp/btl_tcp_component.c:62]: I don't think that this is right -- see https://github.com/open-mpi/ompi/issues/13647#issuecomment-3750598321

Comment (bosilca) [reply opal/mca/btl/tcp/btl_tcp_component.c:62]: I think this is the right fix. According to the autoconf documentation AC_CHECK_HEADERS define the HAVE_* if the header exists, so they will be undefined if the header does not exist. This means we need to use #ifdef and not #if, exactly as with all the other system headers.

Comment (jsquyres) [reply opal/mca/btl/tcp/btl_tcp_component.c:62]: I stand corrected.  

Sidenote: I hate the define-it-or-not-and-therefore-use-ifdef philosophy for exactly these reasons -- mistakes like this fall through the cracks.
