### PR TITLE
Fix ob1 when configured --without-ft

### LINKED ISSUE #9161: SEGFAULT in mca_pml_ob1_recv_req_start
## Background information

Recent versions of the nightly build source code produce a segmentation fault in mca_pml_ob1_recv_req_start(). This occurs on a fresh installation of Amazon Linux (similar to CentOS7) or OpenSUSE Leap. All ranks are run on localhost.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

Nightly source from July 17, 2021:
https://download.open-mpi.org/nightly/open-mpi/master/openmpi-master-202107170241-49c8b33.tar.gz

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

```
./configure --prefix=/opt/ompi --without-ft --disable-man-pages --with-hwloc=internal --enable-debug
make -j4 install
export PATH=/opt/ompi/bin:$PATH
export LD_LIBRARY_PATH=/opt/ompi/lib
```

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

N/A

### Please describe the system on which you are running

* Operating system/version: Amazon Linux 2
* Computer hardware: KVM/QEMU with 8GB RAM and 4 CPUs
* Network type: NAT

* Operating system/version: OpenSUSE Leap 15.3
* Computer hardware: KVM/QEMU with 8GB RAM and 4 CPUs
* Network type: NAT

-----------------------------

## Details of the problem

Two examples are used to produce this issue. First is hello.c:
```
#include <mpi.h>
#include <stdio.h>

int main(int argc, char *argv[])
{
    int rank, size;

    MPI_Init(&argc, &argv);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);

    printf("Hello, World, I am %d of %d\n", rank, size);

    MPI_Finalize();
    return 0;
}
```
Second is conn.c:
```
#include <mpi.h>
#include <stdio.h>

int
main(int argc, char *argv[])
{
    MPI_Status  status;
    int rank, size, peer, len, i, j;
    char host[MPI_MAX_PROCESSOR_NAME];

    MPI_Init(&argc, &argv);
    // Get our rank
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    // Get total ranks
    MPI_Comm_size(MPI_COMM_WORLD, &size);
    if (0 == rank) {
        printf("There are %d ranks in total.\n", size);
    }
    // Get the hostname
    MPI_Get_processor_name(host, &len);
    // Loop through all ranks
    for (i = 0; i < size; i++) {
        if (rank == i) {
            // Send message to all higher ranks
            for (j = i + 1; j < size; j++) {
                printf("%s: %d<->%d\n", host, rank, j);
                MPI_Send(&rank, 1, MPI_INT, j, rank, MPI_COMM_WORLD);
                printf("%s: %d->%d OK\n", host, rank, j);
                MPI_Recv(&peer, 1, MPI_INT, j, j, MPI_COMM_WORLD, &status);
                printf("%s: %d<-%d OK\n", host, rank, j);
            }
            continue;
        }
        if (rank > i) {
            // Receive and reply to message from rank i
            MPI_Recv(&peer, 1, MPI_INT, i, i, MPI_COMM_WORLD, &status);
            MPI_Send(&rank, 1, MPI_INT, i, rank, MPI_COMM_WORLD);
        }
    }
    MPI_Barrier(MPI_COMM_WORLD);
    if (rank == 0) {
        printf("OK.\n");
    }
    MPI_Finalize();
    return 0;
}
```
Programs are compiled as follows:
```
mpicc -g -o hello hello.c
mpicc -g -o conn conn.c
```
Run of hello:
```
mike@localhost:~> mpirun -n 3 -H localhost,localhost,localhost --map-by node:OVERSUBSCRIBE ./hello
Hello, World, I am 1 of 3
Hello, World, I am 2 of 3
Hello, World, I am 0 of 3
mike@localhost:~>
```
Run of conn:
```
mike@localhost:~> mpirun -n 3 -H localhost,localhost,localhost --map-by node:OVERSUBSCRIBE ./conn
There are 3 ranks in total.
localhost: 0<->1
[localhost:18915] *** Process received signal ***
[localhost:18915] Signal: Segmentation fault (11)
[localhost:18915] Signal code:  (128)
[localhost:18915] Failing at address: (nil)
[localhost:18913] *** Process received signal ***
[localhost:18913] Signal: Segmentation fault (11)
[localhost:18913] Signal code: Address not mapped (1)
[localhost:18913] Failing at address: 0x28
[localhost:18914] *** Process received signal ***
[localhost:18914] Signal: Segmentation fault (11)
[localhost:18914] Signal code:  (128)
[localhost:18914] Failing at address: (nil)
[localhost:18914] [ 0] /lib64/libpthread.so.0(+0x13f80)[0x7f5a0cc35f80]
[localhost:18914] [ 1] [localhost:18913] [ 0] /lib64/libpthread.so.0(+0x13f80)[0x7f3b34315f80]
[localhost:18913] [ 1] /opt/ompi/lib/libmpi.so.0(+0x30a224)[0x7f5a0d14c224]
[localhost:18914] [ 2] [localhost:18915] [ 0] /opt/ompi/lib/libmpi.so.0(+0x30a399)[0x7f5a0d14c399]
[localhost:18914] [ 3] /opt/ompi/lib/libmpi.so.0(+0x30a3c0)[0x7f5a0d14c3c0]
[localhost:18914] [ 4] /lib64/libpthread.so.0(+0x13f80)[0x7fd106b69f80]
[localhost:18915] [ 1] /opt/ompi/lib/libmpi.so.0(+0x30a41e)[0x7f5a0d14c41e]
[localhost:18914] [ 5] /opt/ompi/lib/libmpi.so.0(mca_pml_ob1_recv_req_start+0x165)[0x7f3b3483a174]
[localhost:18913] [ 2] /opt/ompi/lib/libmpi.so.0(mca_pml_ob1_isend_init+0x35)[0x7f5a0d14d5fe]
[localhost:18914] [ 6] /opt/ompi/lib/libmpi.so.0(PMPI_Recv+0x2bd)[0x7f5a0cf4fea6]
[localhost:18914] [ 7] ./conn[0x400a53]
[localhost:18914] [ 8] /lib64/libc.so.6(__libc_start_main+0xed)[0x7f5a0c87234d]
[localhost:18914] [ 9] ./conn[0x4007fa]
[localhost:18914] *** End of error message ***
/opt/ompi/lib/libmpi.so.0(+0x30a224)[0x7fd107080224]
/opt/ompi/lib/libmpi.so.0(mca_pml_ob1_iprobe+0x38a)[0x7f3b348264c3]
[localhost:18913] [ 3] [localhost:18915] [ 2] /opt/ompi/lib/libmpi.so.0(MPI_Send+0x2a4)[0x7f3b3463a9d4]
[localhost:18913] [ 4] ./conn[0x400997]
[localhost:18913] [ 5] /lib64/libc.so.6(__libc_start_main+0xed)[0x7f3b33f5234d]
[localhost:18913] [ 6] ./conn[0x4007fa]
[localhost:18913] *** End of error message ***
/opt/ompi/lib/libmpi.so.0(+0x30a399)[0x7fd107080399]
[localhost:18915] [ 3] /opt/ompi/lib/libmpi.so.0(+0x30a3c0)[0x7fd1070803c0]
[localhost:18915] [ 4] /opt/ompi/lib/libmpi.so.0(+0x30a41e)[0x7fd10708041e]
[localhost:18915] [ 5] /opt/ompi/lib/libmpi.so.0(mca_pml_ob1_isend_init+0x35)[0x7fd1070815fe]
[localhost:18915] [ 6] /opt/ompi/lib/libmpi.so.0(PMPI_Recv+0x2bd)[0x7fd106e83ea6]
[localhost:18915] [ 7] ./conn[0x400a53]
[localhost:18915] [ 8] /lib64/libc.so.6(__libc_start_main+0xed)[0x7fd1067a634d]
[localhost:18915] [ 9] ./conn[0x4007fa]
[localhost:18915] *** End of error message ***
--------------------------------------------------------------------------
prterun noticed that process rank 1 with PID 0 on node localhost exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
mike@localhost:~>
```
Examination of core files as reported in a note to @rhc54 
```
Here are the backtraces from the three core files. The second two are both in ompi_group_dense_lookup() when the segfault happens. The first is in the MPI_Send() call and eventually ends up in mca_pml_ob1_recv_req_start(). Guessing this is one of those Star Wars references to Obi-Wan. If I look at the locals in mca_pml_ob1_recv_req_start() I see this:

(gdb) info locals
comm = 0x601080 <ompi_mpi_int>
ob1_comm = 0x0
proc = 0x100400840
frag = 0x7f048ec54000
hdr = 0x200000001
queue = 0x0
__PRETTY_FUNCTION__ = "mca_pml_ob1_recv_req_start"

And the threads from the first coredump:

(gdb) info threads
  Id   Target Id         Frame 
* 1    Thread 0x7f048ec46740 (LWP 19410) 0x00007f048e6b0be4 in mca_pml_ob1_recv_req_start (req=0x7ffd983234d0) at pml_ob1_recvreq.c:1296
  2    Thread 0x7f048c409700 (LWP 19413) 0x00007f048dec23dc in epoll_wait ()
   from /lib64/libc.so.6

And finally, the backtraces:

[ec2-user@novov ompi]$ gdb -q -ex bt ./conn core.19410
Reading symbols from ./conn...done.
[New LWP 19410]
[New LWP 19413]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./conn'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f048e6b0be4 in mca_pml_ob1_recv_req_start (req=0x7ffd983234d0)
    at pml_ob1_recvreq.c:1296
1296           req->req_recv.req_base.req_sequence = ob1_comm->recv_sequence++;
[Current thread is 1 (Thread 0x7f048ec46740 (LWP 19410))]
#0  0x00007f048e6b0be4 in mca_pml_ob1_recv_req_start (req=0x7ffd983234d0)
    at pml_ob1_recvreq.c:1296
#1  0x00007f048e69cf33 in mca_pml_ob1_iprobe (src=-1741538948, tag=1, 
    comm=0x601080 <ompi_mpi_int>, matched=0x1, status=0x0)
    at pml_ob1_iprobe.c:40
#2  0x00007f048e4b1444 in PMPI_Send (buf=0x7ffd9832397c, count=1, 
    type=0x601080 <ompi_mpi_int>, dest=1, tag=0, 
    comm=0x601280 <ompi_mpi_comm_world>) at psend.c:93
#3  0x00000000004009f7 in main (argc=1, argv=0x7ffd98323a88) at conn.c:28
Missing separate debuginfos, use: debuginfo-install glibc-2.26-48.amzn2.x86_64 libgcc-7.3.1-13.amzn2.x86_64
(gdb) q

[ec2-user@novov ompi]$ gdb -q -ex bt ./conn core.19411
Reading symbols from ./conn...done.
[New LWP 19411]
[New LWP 19414]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./conn'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa69ca65c94 in ompi_group_dense_lookup (group=0x7ffc47b632c0, 
    peer_id=0, allocate=true) at ../../../../ompi/group/group.h:356
356             proc = group->grp_proc_pointers[peer_id];
[Current thread is 1 (Thread 0x7fa69d009740 (LWP 19411))]
#0  0x00007fa69ca65c94 in ompi_group_dense_lookup (group=0x7ffc47b632c0, 
    peer_id=0, allocate=true) at ../../../../ompi/group/group.h:356
#1  0x00007fa69ca65e09 in ompi_group_get_proc_ptr (group=0x7ffc47b632c0, 
    rank=0, allocate=true) at ../../../../ompi/group/group.h:394
#2  0x00007fa69ca65e30 in ompi_group_peer_lookup (group=0x7ffc47b632c0, 
    peer_id=0) at ../../../../ompi/group/group.h:423
#3  0x00007fa69ca65e8e in ompi_comm_peer_lookup (comm=0x7ffc47b62220, 
    peer_id=0) at ../../../../ompi/communicator/communicator.h:435
#4  0x00007fa69ca6706e in mca_pml_ob1_isend_init (buf=0x7ffc47b62214, count=1, 
    datatype=0x601080 <ompi_mpi_int>, dst=0, tag=0, sendmode=6296192, 
    comm=0x7ffc47b62220, request=0x7fa69c869850 <PMPI_Recv+503>)
    at pml_ob1_isend.c:52
#5  0x00007fa69c869916 in PMPI_Recv (buf=0x7ffc47b62214, count=1, 
    type=0x601080 <ompi_mpi_int>, source=0, tag=0, 
    comm=0x601280 <ompi_mpi_comm_world>, status=0x7ffc47b62220) at precv.c:97
#6  0x0000000000400ab3 in main (argc=1, argv=0x7ffc47b62328) at conn.c:37
Missing separate debuginfos, use: debuginfo-install glibc-2.26-48.amzn2.x86_64 libgcc-7.3.1-13.amzn2.x86_64
(gdb) q

[ec2-user@novov ompi]$ gdb -q -ex bt ./conn core.19412
Reading symbols from ./conn...done.
[New LWP 19412]
[New LWP 19415]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./conn'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f604bff1c94 in ompi_group_dense_lookup (group=0x7ffefcaea2c0, 
    peer_id=0, allocate=true) at ../../../../ompi/group/group.h:356
356             proc = group->grp_proc_pointers[peer_id];
[Current thread is 1 (Thread 0x7f604c595740 (LWP 19412))]
#0  0x00007f604bff1c94 in ompi_group_dense_lookup (group=0x7ffefcaea2c0, 
    peer_id=0, allocate=true) at ../../../../ompi/group/group.h:356
#1  0x00007f604bff1e09 in ompi_group_get_proc_ptr (group=0x7ffefcaea2c0, 
    rank=0, allocate=true) at ../../../../ompi/group/group.h:394
#2  0x00007f604bff1e30 in ompi_group_peer_lookup (group=0x7ffefcaea2c0, 
    peer_id=0) at ../../../../ompi/group/group.h:423
#3  0x00007f604bff1e8e in ompi_comm_peer_lookup (comm=0x7ffefcae9250, 
    peer_id=0) at ../../../../ompi/communicator/communicator.h:435
#4  0x00007f604bff306e in mca_pml_ob1_isend_init (buf=0x7ffefcae9244, count=1, 
    datatype=0x601080 <ompi_mpi_int>, dst=0, tag=0, sendmode=6296192, 
    comm=0x7ffefcae9250, request=0x7f604bdf5850 <PMPI_Recv+503>)
    at pml_ob1_isend.c:52
#5  0x00007f604bdf5916 in PMPI_Recv (buf=0x7ffefcae9244, count=1, 
    type=0x601080 <ompi_mpi_int>, source=0, tag=0, 
    comm=0x601280 <ompi_mpi_comm_world>, status=0x7ffefcae9250) at precv.c:97
#6  0x0000000000400ab3 in main (argc=1, argv=0x7ffefcae9358) at conn.c:37
Missing separate debuginfos, use: debuginfo-install glibc-2.26-48.amzn2.x86_64 libgcc-7.3.1-13.amzn2.x86_64
(gdb) q
```

### PR DESCRIPTION
**Pull request by rhc54**
Use C99 syntax to ensure fields are properly populated.

Fixes #9161

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

File: ompi/mca/pml/ob1/pml_ob1.c [hunk 1]
```diff
@@ -60,32 +61,32 @@
...
+        .pml_add_procs      = mca_pml_ob1_add_procs,
+        .pml_del_procs      = mca_pml_ob1_del_procs,
+        .pml_enable         = mca_pml_ob1_enable,
+        .pml_progress       = NULL,  /* mca_pml_ob1_progress, */
+        .pml_add_comm       = mca_pml_ob1_add_comm,
+        .pml_del_comm       = mca_pml_ob1_del_comm,
 #if OPAL_ENABLE_FT_MPI
-        mca_pml_ob1_revoke_comm,
+        .pml_revoke_comm    = mca_pml_ob1_revoke_comm,
 #endif
```
Comment (bwbarrett) [inline ompi/mca/pml/ob1/pml_ob1.c:72]: This is technically correct (the best kind!), but it feels like it would be more readable to those who do not remember initialization rules to explicitly set `pml_revoke_comm` to `NULL` in the `#else` case.

**Review by bwbarrett — APPROVED** [review]

File: ompi/mca/pml/ob1/pml_ob1.c (hunk 1 above)
Comment (rhc54) [reply ompi/mca/pml/ob1/pml_ob1.c:74]: Good point - done!

**Review by bwbarrett — APPROVED** [review]
