### PR TITLE
mpi/neighbor_allgatherv: fix copy&paste error and add helpers

### LINKED ISSUE #2324: Neighborhood Collectives
@jsquyres I've found serious issues in the implementation of neighborhood collectives. These issues showed up after a memory allocation optimization I've implemented in mpi4py in commit [c2eaa292](https://bitbucket.org/mpi4py/mpi4py/commits/c2eaa292b2aa1d4bf809c91a1c19d988629f009a), which failed badly with Open MPI 2.0.1 in this [Bitbucket Pipelines](https://bitbucket.org/mpi4py/mpi4py/addon/pipelines/home#!/results/%7B8c67bd67-9cd6-4251-94b9-c96bf375c7a3%7D) build.

After checking the source code in ompi/v2.x, I found a major issue for the case of intracommunicators with a topology. The code simply do not check the topology to determine the number or sources and destinations, and use ``ompi_comm_size()`` instead. This leads to wrong checks and reads after end of arrays.

In mpi4py, I'm using the following [code](https://bitbucket.org/mpi4py/mpi4py/src/master/src/mpi4py/MPI/commimpl.pxi?fileviewer=file-view-default#commimpl.pxi-49) to determine the number of sources and destinations. This piece of code only handles intracommunicators, but could be extended to intercommunicators.

BTW, the wording of the MPI standard seems to require a topology for neighborhood collectives, although supporting intracomms and intercomms seems possible and the result should be equivalent to regular allgather and alltoall. Or maybe the right thing to do is to just error in case of intercomms or intracomms with no topology.

Am I missing something?

PS: MPICH seems to implement neighbor collectives just for Cartesian/graph topologies, the helper routine `MPIR_Topo_canon_nhb_count` is quite similar to what I'm using in mpi4py (though the MPICH one fails in case of no topology). @roblatham00 Any comments to you competitors :-) about this?

```
$[dalcinl@localhost mpich.git]$ git grep MPIR_Topo_canon_nhb_count
src/include/mpir_topo.h:int MPIR_Topo_canon_nhb_count(MPIR_Comm *comm_ptr, int *indegree, int *outdegree, int *weighted);
src/mpi/topo/inhb_allgather.c:    mpi_errno = MPIR_Topo_canon_nhb_count(comm_ptr, &indegree, &outdegree, &weighted);
src/mpi/topo/inhb_allgatherv.c:    mpi_errno = MPIR_Topo_canon_nhb_count(comm_ptr, &indegree, &outdegree, &weighted);
src/mpi/topo/inhb_alltoall.c:    mpi_errno = MPIR_Topo_canon_nhb_count(comm_ptr, &indegree, &outdegree, &weighted);
src/mpi/topo/inhb_alltoallv.c:    mpi_errno = MPIR_Topo_canon_nhb_count(comm_ptr, &indegree, &outdegree, &weighted);
src/mpi/topo/inhb_alltoallw.c:    mpi_errno = MPIR_Topo_canon_nhb_count(comm_ptr, &indegree, &outdegree, &weighted);
src/mpi/topo/topoutil.c:#define FUNCNAME MPIR_Topo_canon_nhb_count
src/mpi/topo/topoutil.c:int MPIR_Topo_canon_nhb_count(MPIR_Comm *comm_ptr, int *indegree, int *outdegree, int *weighted)
```

### PR DESCRIPTION
**Pull request by hjelmn**
This commit adds a helper function to get the inbound and outbound
neighbor count and updates the neighbor_allgatherv bindings to use the
correct count when checking the input parameters.

Fixes #2324

Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>
(cherry picked from commit 3c0e94afab03a27364114dcf3d429943d15cd4f4)
Signed-off-by: Nathan Hjelm <hjelmn@me.com>

### CODE REVIEW

**Comment by hjelmn** [comment]
Punt to 3.0.1 if needed. Do not let this hold anything up.

File: ompi/mca/topo/base/topo_base_frame.c [hunk 1]
```diff
@@ -71,6 +71,33 @@ static int mca_topo_base_open(mca_base_open_flag_t flags)
...
+    /* graph */
+    int rank, nneighbors;
+
+    rank = ompi_comm_rank (comm);
+    mca_topo_base_graph_neighbors_count (comm, rank, &nneighbors);
+
+    *outdegree = *indegree = nneighbors;
+  } else if (OMPI_COMM_IS_DIST_GRAPH(comm)) {
+    /* graph */
+    *indegree = comm->c_topo->mtc.dist_graph->indegree;
```
Comment (ggouaillardet) [inline ompi/mca/topo/base/topo_base_frame.c]: you could use ```mca_topo_base_dist_graph_neighbors_count()``` instead

more generally speaking, is there any reason why you invoke these base functions directly instead of using the callbacks
(for example ```module->topo.dist_graph.dist_graph_neighbors_count()```)

**Comment by hppritcha** [comment]
@hjelmn have you and @ggouaillardet come to a consensus on this?  we'd like to get this in today or latest tomorrow morning in time for an rc2.

**Comment by hjelmn** [comment]
@hppritcha Yes. I need to add one more commit to this then it is good to go.

**Comment by hjelmn** [comment]
ok, should be good now.

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by jjhursey** [comment]
bot:ibm:pgi:retest
bot:ibm:xl:retest

**Comment by hppritcha** [comment]
Sign off checker seems to be confused.  Maybe because the commits are doubly signed.

**Comment by hppritcha** [comment]
@ggouaillardet please recheck
