### PR TITLE
Java garbage collection bugfix

### LINKED ISSUE #369: Persistent communication request provokes segfault in Java bindings.
MPI corrupts the memory space of Java.
The following example provokes segfault in Java bindings.
Please, see the comments in the example.

```java
import mpi.*;                                                                         
import java.nio.*;                                                                    

public class CrashTest
{
    private static final int STEPS = 1000000000,
        SIZE  = 4096;

    public static void main(String...args) throws MPIException
    {
        MPI.Init(args);
        int rank = MPI.COMM_WORLD.getRank();
        StringBuilder s = new StringBuilder();

        if(MPI.COMM_WORLD.getSize() != 2)
            throw new MPIException("I need exactly 2 processes.");

        // Only one buffer is needed,                                                 
        // but the test works ok if you only use one.                                 
        ByteBuffer sendBuf = MPI.newByteBuffer(SIZE),
            recvBuf = MPI.newByteBuffer(SIZE);

        Prequest req = MPI.COMM_WORLD.recvInit(recvBuf, SIZE, MPI.BYTE, 0, 0);

        for(int i = 1; i <= STEPS; i++)
            {
                // Allocate memory to provoke GC work and crash.                      
                // If you comment the following line, the test works ok.              
                (s = new StringBuilder(SIZE).append(i)).trimToSize();

                if(rank == 0)
                    {
                        if(i % 100000 == 0)
                            {
                                s.setLength(0);
                                System.out.println(i + s.toString());
                            }

                        MPI.COMM_WORLD.send(sendBuf, SIZE, MPI.BYTE, 1, 0);
                    }
                else
                    {
                        req.start();
                        req.waitFor();
                    }
            }

        MPI.Finalize();
    }

} // CrashTest
```

### PR DESCRIPTION
**Pull request by nrgraham23**
This pull request adds two Buffer references to the 
Request class.  Whenever a request object is created
that has associated buffers, the buffers should be added
to these references so the java garbage collector does
not dispose of the buffers prematurely.

This is a more robust expansion on the idea first proposed by
@ggouaillardet, and further discussed in #369.

Fixes #369

Signed-off-by: Nathaniel Graham <ngraham@lanl.gov>

@hppritcha @jsquyres @ggouaillardet @osvegis

### CODE REVIEW

File: ompi/mpi/java/java/Comm.java [hunk 1]
```diff
@@ -162,12 +162,12 @@ public Comm iDup() throws MPIException
 	 */
 	public Comm dupWithInfo(Info info) throws MPIException
 	{
-	    MPI.check();
-	    return new Comm(dupWithInfo(handle, info.handle));
+		MPI.check();
+		return new Comm(dupWithInfo(handle, info.handle));
```
Comment (hppritcha) [inline ompi/mpi/java/java/Comm.java]: minor thing, and don't redo for this PR, but normally try to avoid whitespace changes in PRs that are not just whitespace changes.

**Comment by hppritcha** [comment]
:+1:

**Comment by hppritcha** [comment]
@nrgraham23 please push this fix back to v1.10.
