### PR TITLE
osc/rdma: Fix MPI_Win_start()/complete() with MPI_GROUP_EMPTY.

### LINKED ISSUE #8677: Regression: MPI_Win_start()/complete() with MPI_GROUP_EMPTY
I don't consider myself an expert on OSC, but the following code used to work across MPI implementations. Now it is failing with current master.

Reproducer
```python
from mpi4py import MPI  # Implies MPI_Init_thread() with MPI_THREAD_MULTIPLE

buf = MPI.Alloc_mem(1024)
win = MPI.Win.Create(buf, 1, MPI.INFO_NULL, MPI.COMM_SELF)
win.Start(MPI.GROUP_EMPTY)
win.Complete()
win.Free()
MPI.Free_mem(buf)
```
Output:
```
Traceback (most recent call last):
  File "/tmp/rma.py", line 5, in <module>
    win.Complete()
  File "mpi4py/MPI/Win.pyx", line 592, in mpi4py.MPI.Win.Complete
mpi4py.MPI.Exception: MPI_ERR_RMA_SYNC: error executing rma sync
```

### PR DESCRIPTION
**Pull request by awlauria**
- Make sure the epoch type is set before returning from MPI_Win_start().
- Make sure the group is only free'd if it is valid in MPI_Win_complete().
  - Fix possible double free() of the group.

Fixes #8677

Signed-off-by: Austen Lauria <awlauria@us.ibm.com>

### CODE REVIEW

**Comment by awlauria** [comment]
@hjelmn ping - can you take a quick look when you have some cycles. Thanks!

**Comment by dalcinl** [comment]
@gpaulsen maybe you can ask someone else to review this PR? The fixes are rather trivial.

**Comment by awlauria** [comment]
@devreal / @bosilca do you mind giving this a quick look? This bug is blocking @dalcinl .

**Comment by bosilca** [comment]
The asymmetry proposed by the patch looks strange to me. Basically you always start an epoch but only increase the refcount on the group when there are processes in the group (group of size zero and not the MPI_GROUP_EMPTY). On the other side you release the refcount if the group is not MPI_GROUP_EMPTY, which indicate that 0-process groups will see their refcount reduced, while they did not go through the proper refcount increase. But I might misread the commit, and/or miss some other checks at the upper level that would provide a shortcut for groups with no processes (but that are not MPI_GROUP_EMPTY)

**Comment by awlauria** [comment]
@bosilca I agree - I restored the symmetry.

File: ompi/mca/osc/rdma/osc_rdma_active_target.c [hunk 1]
```diff
@@ -385,6 +385,8 @@ int ompi_osc_rdma_start_atomic (ompi_group_t *group, int mpi_assert, ompi_win_t
 
     OSC_RDMA_VERBOSE(MCA_BASE_VERBOSE_TRACE, "start group size %d", sync->num_peers);
 
+    sync->type = OMPI_OSC_RDMA_SYNC_TYPE_PSCW;
+
     if (0 == ompi_group_size (group)) {
         /* nothing more to do. this is an empty start epoch */
```
Comment (dalcinl) [inline ompi/mca/osc/rdma/osc_rdma_active_target.c:391]: I believe you are missing the following initialization, cf. the code in the complete operation.

```suggestion
        /* nothing more to do. this is an empty start epoch */
        sync->peer_list.peers = NULL;
```

**Comment by awlauria** [comment]
@bosilca @hjelmn ping - please re-review.

File: ompi/mca/osc/rdma/osc_rdma_active_target.c (hunk 1 above)
Comment (awlauria) [reply ompi/mca/osc/rdma/osc_rdma_active_target.c:391]: I agree based on code inspection.

**Comment by awlauria** [comment]
bot:aws:retest

File: ompi/mca/osc/rdma/osc_rdma_active_target.c (hunk 1 above)
Comment (awlauria) [reply ompi/mca/osc/rdma/osc_rdma_active_target.c:391]: @dancejic I squashed this commit down and added you as co-author. Thanks!
