### PR TITLE
Extract 3rd party configure options for OMPI configure

### LINKED ISSUE #7486: Re-enable runtime-enabled `configure` CLI params (to pass to PRRTE)
The master README currently still describes the following `configure` CLI params:

* --enable-orte-static-ports
* --with-alps
* --with-lsf[-libdir]
* --with-pmi
* --with-slurm
* --with-sge
* --with-tm

With the exception of `--with-pmi` (which is already handled) and `--enable-orte-static-ports` (see below), they others don't seem to exist in OMPI's `./configure --help` output any more.  Some plumbing needs to be put in to support this kind of functionality in some manner (e.g., just pass them directly through to PRRTE's `configure`, or ...something else...).

I don't know if PRRTE supports static ports like ORTE did, but if so, that one should probably be plumed through, too.  If not, `--enable-orte-static-ports` should probably be added to `ompi_deleted_options.m4`.

In Slack discussions, @jjhursey volunteered to look at this.

### PR DESCRIPTION
**Pull request by jjhursey**
* Closes #7486
 * Harvest 3rd party configure options into OMPI's upper-level configure
 * Deduplicate configure options provided by multiple packages by preferring the OMPI version when available.

### CODE REVIEW

**Comment by jjhursey** [comment]
Details on the design are [here](https://github.com/open-mpi/ompi/issues/7486#issuecomment-765959752)

Left to do:
 * Re-enable this for hwloc and libevent
 * Refine the exclude file for all 3rd party projects

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/4b6fada13a807035962312569f72d2a7

**Comment by bwbarrett** [comment]
The revert should definitely be committed, as that patch should really never have been added.  `./configure --help=recursive` is the proper way to handle subconfigure options.  We shouldn't be inventing our own option.

I obviously think the scripts to replicate the behavior of `./configure --help=recursive` should not be committed, for the same reason.

I'm curious the use case for having a different location of SLURM (or similar) for Open MPI and PRRTE.  I talked to Ralph when doing the initial work, and we could not come up with one that seemed useful enough for that code (and the complexity of users accidentally specifying a package enablement to prrte but not pmix, for example.  So I'd really rather we not add that functionality without a bunch more discussion.

**Comment by jjhursey** [comment]
Let's continue the discussion on the original ticket to reach a resolution: Issue #7486

File: autogen.pl [hunk 1]
```diff
@@ -1481,6 +1481,11 @@ sub in_tarball {
     $m4 .= "m4_define([package_libevent], [1])\n";
     $m4 .= "m4_define([libevent_tarball], [" . $libevent_tarball . "])\n";
     $m4 .= "m4_define([libevent_directory], [" . $libevent_directory . "])\n";
+
+    # Grab the unique configure options from each of the 3rd party packages
+    # JJH Re-enable
+    #system("./config/extract-3rd-party-configure.pl -p \"3rd-party/".$libevent_directory."/\" -n \"Libevent\" -m > config/auto-libevent.m4");
```
Comment (bwbarrett) [inline autogen.pl:1487]: I know it's commented out, but I'm not sure we should support this for libevent.  We auto-add a bunch of arguments to our internal libevent (in part, to make sure we don't pull in even more dependencies, like suddenly having an SSL dependency).  I'd be really leery of supporting pulling trying to support all those configurations of libevent.  Similar argument with hwloc, although we don't pre-set nearly as many options there.

Add to that, we intentionally don't expand the tarball in autogen.pl, so that makes it doubly hard.

File: autogen.pl [hunk 2]
```diff
@@ -1509,6 +1519,10 @@ sub in_tarball {
     }
     push(@subdirs, "3rd-party/openpmix/");
     $m4 .= "m4_define([package_pmix], [1])\n";
+
+    # Grab the unique configure options from each of the 3rd party packages
+    system("./config/extract-3rd-party-configure.pl -p \"3rd-party/openpmix/\" -n \"PMIx\" -m > config/auto-pmix.m4");
```
Comment (bwbarrett) [inline autogen.pl:1524]: don't forget to check and handle the return code.  We should abort configure if this fails.

File: autogen.pl [hunk 3]
```diff
@@ -1554,6 +1572,7 @@ sub in_tarball {
     print "<none found>\n";
 }
 
+
```
Comment (bwbarrett) [inline autogen.pl:1575]: Unnecessary change?

File: config/opal_config_pmix.m4 [hunk 4]
```diff
@@ -63,6 +63,8 @@ AC_DEFUN([OPAL_CONFIG_PMIX], [
 
     OPAL_3RDPARTY_WITH([pmix], [pmix], [package_pmix])
 
+    OMPI_PMIX_ADD_ARGS
```
Comment (bwbarrett) [inline config/opal_config_pmix.m4:66]: This should be inside the m4_ifdef on line 71; we should not add PMIx subconfigure args if we did not set package_pmix.

**Review by bwbarrett — COMMENTED** [review]
I only reviewed the first two patches, since the third (the renaming patch) won't be needed.

File: autogen.pl (hunk 1 above)
Comment (jjhursey) [reply autogen.pl:1583]: I agree. I'll remove in the next push.

File: autogen.pl (hunk 2 above)
Comment (jjhursey) [reply autogen.pl:1620]: Will be fixed in the next push.

File: .gitignore [hunk 5]
```diff
@@ -114,6 +114,8 @@ config/mca_no_configure_components.m4
 config/mca_m4_config_include.m4
 config/ext_no_configure_components.m4
 config/ext_m4_config_include.m4
+config/auto-pmix.m4
```
[the remark this answers is not in the document]
Comment (jjhursey) [reply .gitignore:117]: A little verbose, but I went with `config/auto-extracted-pmix-configure-args.m4`

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/5615c1a7775061c962eff24177407c74

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/de5b15c36702fd93cb8d4ab92ec46ee0

**Comment by ibm-ompi** [comment]
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/e032e1c88eb0b91c04b8aecdc6a07eed

File: config/opal_config_pmix.m4 (hunk 4 above)
Comment (jjhursey) [reply config/opal_config_pmix.m4]: done

File: 3rd-party/exclude-config.ini [hunk 6]
```diff
@@ -0,0 +1,49 @@
+#
+# Copyright (c) 2021      IBM Corporation.  All rights reserved.
+# $COPYRIGHT$
+#
+# Additional copyrights may follow
+#
```
[the remark this answers is not in the document]
Comment (jjhursey) [reply 3rd-party/exclude-config.ini:6]: Done

**Comment by jjhursey** [comment]
Left to do:
 * Audit the `exclude-config.ini`
 * Deduplicate configure options (see note [here](https://github.com/open-mpi/ompi/issues/7486#issuecomment-790088989) )

**Comment by jjhursey** [comment]
This PR is now ready for review. I believe that it has addressed all of the requirements that the community has defined for this functionality from Issue #7486.

**Review by bwbarrett — APPROVED** [review]

**Comment by jjhursey** [comment]
Does anyone else want to review before I merge? Otherwise, I'll bring this in tomorrow.
