### PR TITLE
opal/event: use epoll by default on Linux

### LINKED ISSUE #10929: Significant performance regression under Linux with busy waiting enabled
Thank you for taking the time to submit an issue!

## Background information

I am looking at a system which is showing very poor performance with some applications (notably OpenFOAM) when running Open MPI. The system in question has busy polling enabled to (in theory) improve message latency:

```
==> /proc/sys/net/core/busy_poll <==
50

==> /proc/sys/net/core/busy_read <==
50
```

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

v4.1.x, main, etc

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Both from release tarball and git checkout.

### Please describe the system on which you are running

* Operating system/version: Linux 3.10.0-1160.76.1.el7.x86_64
* Computer hardware: Intel Xeon
* Network type: 100 GigE

-----------------------------

## Details of the problem

With these settings we see a 3-5x slowdown in the performance of all steps of OpenFOAM motorbike (can give run details if requested) vs with them both set to 0 (busy waiting disabled).

Without busy polling:

```
Finished meshing in = 24.9 s
ExecutionTime = 41.7 s  ClockTime = 44 s
```

With busy polling:

```
Finished meshing in = 73.02 s.
ExecutionTime = 109.37 s  ClockTime = 112 s
```

The only difference between these runs is busy polling enabled vs disabled.

### PR DESCRIPTION
**Pull request by hjelmn**
Under normal circumstances epoll and poll produce similar performance on Linux. When busy polling is enabled they do not. Testing with a TCP-based system shows a significan performance degredation when using poll with busy waiting enabled. This performance regression is not seen when using epoll. This PR adjusts the default value of opal_event_include to epoll on Linux only to fix the regression.

Fixes #10929

Signed-off-by: Nathan Hjelm <hjelmn@google.com>

### CODE REVIEW

File: opal/util/event.c [hunk 1]
```diff
@@ -47,6 +48,8 @@ int opal_event_register_params(void)
 
 #ifdef __APPLE__
     opal_event_module_include = "select";
+#elif defined(__linux__)
```
Comment (bwbarrett) [inline opal/util/event.c:51]: We should really use the PLATFORM macros here, so:
```
#if defined(PLATFORM_OS_LINUX)
```

**Review by bwbarrett — APPROVED** [review]

File: opal/util/event.c (hunk 1 above)
Comment (hjelmn) [reply opal/util/event.c]: Done. Also changed the __APPLE__ one to PLATFORM_OS_DARWIN.

**Review by bwbarrett — APPROVED** [review]

**Comment by hjelmn** [comment]
:bot:ibm:retest

**Comment by jsquyres** [comment]
@hjelmn Will you cherry-pick to v5.0.x?

**Comment by rhc54** [comment]
Just curious: we have multiple projects initializing the common event library. If they call that init function with different arguments, which one gets used? I suspect it is the first caller that sets things, but is that a tad fragile (e.g., if someone changes the code init sequence so PMIx goes first - which I think we were doing at one point)? Are we in trouble if the second (or later) library actually depends on a particular setting?

I'm wondering if we need to set some kind of global envar that the libraries can pick up to ensure they set things up as desired.
