### PR TITLE
Fix a bunch of compiler warnings 

### LINKED ISSUE #9406: btl/rdma warnings
Current head of master:
```c
base/btl_base_am_rdma.c:200:29: warning: invalid use of structure with flexible array member [-Wpedantic]
  200 |     mca_btl_base_rdma_hdr_t hdr;
      |                             ^~~
In file included from ../../../opal/class/opal_list.h:77,
                 from ../../../opal/class/opal_lifo.h:32,
                 from ../../../opal/class/opal_free_list.h:28,
                 from ../../../opal/mca/mpool/mpool.h:30,
                 from ../../../opal/mca/btl/btl.h:124,
                 from ../../../opal/mca/btl/base/btl_base_am_rdma.h:23,
                 from base/btl_base_am_rdma.c:14:
base/btl_base_am_rdma.c: In function 'mca_btl_base_am_rdma_progress':
base/btl_base_am_rdma.c:768:52: warning: ISO C forbids braced-groups within expressions [-Wpedantic]
  768 |     OPAL_THREAD_SCOPED_LOCK(&default_module.mutex, ({
      |                                                    ^
../../../opal/mca/threads/mutex.h:253:13: note: in definition of macro 'OPAL_THREAD_SCOPED_LOCK'
  253 |             action;                                \
      |             ^~~~~~
base/btl_base_am_rdma.c:768:52: warning: ISO C forbids braced-groups within expressions [-Wpedantic]
  768 |     OPAL_THREAD_SCOPED_LOCK(&default_module.mutex, ({
      |                                                    ^
../../../opal/mca/threads/mutex.h:256:13: note: in definition of macro 'OPAL_THREAD_SCOPED_LOCK'
  256 |             action;                                \
      |             ^~~~~~
base/btl_base_am_rdma.c:776:52: warning: ISO C forbids braced-groups within expressions [-Wpedantic]
  776 |     OPAL_THREAD_SCOPED_LOCK(&default_module.mutex, ({
      |                                                    ^
../../../opal/mca/threads/mutex.h:253:13: note: in definition of macro 'OPAL_THREAD_SCOPED_LOCK'
  253 |             action;                                \
      |             ^~~~~~
base/btl_base_am_rdma.c:776:52: warning: ISO C forbids braced-groups within expressions [-Wpedantic]
  776 |     OPAL_THREAD_SCOPED_LOCK(&default_module.mutex, ({
      |                                                    ^
../../../opal/mca/threads/mutex.h:256:13: note: in definition of macro 'OPAL_THREAD_SCOPED_LOCK'
  256 |             action;                                \
      |             ^~~~~~
base/btl_base_am_rdma.c: In function 'mca_btl_base_am_process_atomic':
base/btl_base_am_rdma.c:970:39: warning: pointer targets in passing argument 1 of 'mca_btl_base_am_atomic_32' differ in signedness [-Wpointer-sign]
  970 |             mca_btl_base_am_atomic_32(&tmp, (opal_atomic_int32_t *) (uintptr_t) hdr->target_address,
      |                                       ^~~~
      |                                       |
      |                                       uint32_t * {aka unsigned int *}
base/btl_base_am_rdma.c:830:47: note: expected 'int32_t *' {aka 'int *'} but argument is of type 'uint32_t *' {aka 'unsigned int *'}
  830 | static int mca_btl_base_am_atomic_32(int32_t *operand, opal_atomic_int32_t *addr,
      |                                      ~~~~~~~~~^~~~~~~
base/btl_base_am_rdma.c:975:39: warning: pointer targets in passing argument 1 of 'mca_btl_base_am_atomic_64' differ in signedness [-Wpointer-sign]
  975 |             mca_btl_base_am_atomic_64(&atomic_response,
      |                                       ^~~~~~~~~~~~~~~~
      |                                       |
      |                                       uint64_t * {aka long long unsigned int *}
base/btl_base_am_rdma.c:795:47: note: expected 'int64_t *' {aka 'long long int *'} but argument is of type 'uint64_t *' {aka 'long long unsigned int *'}
  795 | static int mca_btl_base_am_atomic_64(int64_t *operand, opal_atomic_int64_t *addr,
      |                                      ~~~~~~~~~^~~~~~~
```

### LINKED ISSUE #9407: pml/ob1 warnings
Current head of master:
```c
pml_ob1_isend.c: In function 'mca_pml_ob1_isend':
pml_ob1_isend.c:228:29: warning: passing argument 2 of 'opal_output_check_verbosity' makes integer from pointer without a cast [-Wint-conversion]
  228 |     OPAL_OUTPUT_VERBOSE((2, "Allocating request in error %s (peer %d, seq %d) with error code %d", sendreq, dst, sendreq->req_send.req_base.req_sequence, sendreq->req_send.req_base.req_ompi.req_status.MPI_ERROR));
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                             |
      |                             char *
../../../../opal/util/output.h:409:56: note: in definition of macro 'opal_output_verbose'
  409 |         if (opal_output_check_verbosity(verbose_level, output_id)) { \
      |                                                        ^~~~~~~~~
pml_ob1_isend.c:228:5: note: in expansion of macro 'OPAL_OUTPUT_VERBOSE'
  228 |     OPAL_OUTPUT_VERBOSE((2, "Allocating request in error %s (peer %d, seq %d) with error code %d", sendreq, dst, sendreq->req_send.req_base.req_sequence, sendreq->req_send.req_base.req_ompi.req_status.MPI_ERROR));
      |     ^~~~~~~~~~~~~~~~~~~
../../../../opal/util/output.h:414:71: note: expected 'int' but argument is of type 'char *'
  414 | OPAL_DECLSPEC bool opal_output_check_verbosity(int verbose_level, int output_id);
      |                                                                   ~~~~^~~~~~~~~
pml_ob1_isend.c:228:29: warning: passing argument 1 of 'opal_output' makes integer from pointer without a cast [-Wint-conversion]
  228 |     OPAL_OUTPUT_VERBOSE((2, "Allocating request in error %s (peer %d, seq %d) with error code %d", sendreq, dst, sendreq->req_send.req_base.req_sequence, sendreq->req_send.req_base.req_ompi.req_status.MPI_ERROR));
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                             |
      |                             char *
../../../../opal/util/output.h:410:25: note: in definition of macro 'opal_output_verbose'
  410 |             opal_output(output_id, __VA_ARGS__);                     \
      |                         ^~~~~~~~~
pml_ob1_isend.c:228:5: note: in expansion of macro 'OPAL_OUTPUT_VERBOSE'
  228 |     OPAL_OUTPUT_VERBOSE((2, "Allocating request in error %s (peer %d, seq %d) with error code %d", sendreq, dst, sendreq->req_send.req_base.req_sequence, sendreq->req_send.req_base.req_ompi.req_status.MPI_ERROR));
      |     ^~~~~~~~~~~~~~~~~~~
../../../../opal/util/output.h:376:36: note: expected 'int' but argument is of type 'char *'
  376 | OPAL_DECLSPEC void opal_output(int output_id, const char *format, ...)
      |                                ~~~~^~~~~~~~~
pml_ob1_isend.c:228:100: warning: passing argument 2 of 'opal_output' from incompatible pointer type [-Wincompatible-pointer-types]
  228 |     OPAL_OUTPUT_VERBOSE((2, "Allocating request in error %s (peer %d, seq %d) with error code %d", sendreq, dst, sendreq->req_send.req_base.req_sequence, sendreq->req_send.req_base.req_ompi.req_status.MPI_ERROR));
      |                                                                                                    ^~~~~~~
      |                                                                                                    |
      |                                                                                                    mca_pml_ob1_send_request_t * {aka struct mca_pml_ob1_send_request_t *}
../../../../opal/util/output.h:410:36: note: in definition of macro 'opal_output_verbose'
  410 |             opal_output(output_id, __VA_ARGS__);                     \
      |                                    ^~~~~~~~~~~
pml_ob1_isend.c:228:5: note: in expansion of macro 'OPAL_OUTPUT_VERBOSE'
  228 |     OPAL_OUTPUT_VERBOSE((2, "Allocating request in error %s (peer %d, seq %d) with error code %d", sendreq, dst, sendreq->req_send.req_base.req_sequence, sendreq->req_send.req_base.req_ompi.req_status.MPI_ERROR));
      |     ^~~~~~~~~~~~~~~~~~~
../../../../opal/util/output.h:376:59: note: expected 'const char *' but argument is of type 'mca_pml_ob1_send_request_t *' {aka 'struct mca_pml_ob1_send_request_t *'}
  376 | OPAL_DECLSPEC void opal_output(int output_id, const char *format, ...)
      |                                               ~~~~~~~~~~~~^~~~~~
In file included from ../../../../opal/mca/threads/pthreads/threads_pthreads_mutex.h:51,
                 from ../../../../opal/mca/threads/mutex.h:53,
                 from ../../../../opal/class/opal_list.h:77,
                 from pml_ob1_recvfrag.c:36:
pml_ob1_recvfrag.c: In function 'mca_pml_ob1_recv_frag_callback_ack':
pml_ob1_recvfrag.c:684:59: warning: format '%d' expects argument of type 'int', but argument 4 has type 'uint64_t' {aka 'long long unsigned int'} [-Wformat=]
  684 |         OPAL_OUTPUT_VERBOSE((2, ompi_ftmpi_output_handle, "Recvfrag: Received a NACK to the RDV/RGET match to %d for seq %d on comm %d\n", sendreq->req_send.req_base.req_peer, sendreq->req_send.req_base.req_sequence, sendreq->req_send.req_base.req_comm->c_contextid));
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                                                                           |
      |                                                                                                                                                                                                           uint64_t {aka long long unsigned int}
../../../../opal/util/output.h:410:36: note: in definition of macro 'opal_output_verbose'
  410 |             opal_output(output_id, __VA_ARGS__);                     \
      |                                    ^~~~~~~~~~~
pml_ob1_recvfrag.c:684:9: note: in expansion of macro 'OPAL_OUTPUT_VERBOSE'
  684 |         OPAL_OUTPUT_VERBOSE((2, ompi_ftmpi_output_handle, "Recvfrag: Received a NACK to the RDV/RGET match to %d for seq %d on comm %d\n", sendreq->req_send.req_base.req_peer, sendreq->req_send.req_base.req_sequence, sendreq->req_send.req_base.req_comm->c_contextid));
      |         ^~~~~~~~~~~~~~~~~~~
pml_ob1_recvfrag.c:684:123: note: format string is defined here
  684 |         OPAL_OUTPUT_VERBOSE((2, ompi_ftmpi_output_handle, "Recvfrag: Received a NACK to the RDV/RGET match to %d for seq %d on comm %d\n", sendreq->req_send.req_base.req_peer, sendreq->req_send.req_base.req_sequence, sendreq->req_send.req_base.req_comm->c_contextid));
```

### PR DESCRIPTION
**Pull request by jsquyres**
This fixes a bunch of compiler warnings.  When this PR is complete, it should be cherry picked to v5.0.x.

This PR fixes #9407 (these are legit bugs, not just compiler warnings).

This PR _partially_ fixes #9406.  Need advice from @hjelmn on how to fix the rest of #9406.

### CODE REVIEW

File: ompi/mca/coll/ftagree/coll_ftagree_earlyreturning.c [hunk 1]
```diff
@@ -3234,7 +3235,11 @@ int mca_coll_ftagree_era_inter(void *contrib,
     ompi_group_free(&uniongrp);
     shadowcomm->c_contextid = comm->c_contextid;
     shadowcomm->c_epoch = comm->c_epoch;
-    snprintf(shadowcomm->c_name, MPI_MAX_OBJECT_NAME, "SHADOW OF %s", &comm->c_name[0]);
+    // Use opal_snprintf() so that we don't get a compiler warning
```
Comment (bwbarrett) [inline ompi/mca/coll/ftagree/coll_ftagree_earlyreturning.c:3238]: We should ditch the comment.  We have opal_snprintf, which means we should always use it instead of snprintf...

File: opal/mca/btl/base/btl_base_am_rdma.c [hunk 2]
```diff
@@ -765,29 +765,39 @@ static int mca_btl_base_am_rdma_progress(void)
...
-            int ret = descriptor->btl->btl_send(descriptor->btl, descriptor->endpoint,
-                                                descriptor->descriptor,
-                                                mca_btl_base_rdma_tag(context->type));
-            if (OPAL_SUCCESS == ret) {
-                opal_list_remove_item(&default_module.queued_initiator_descriptors,
-                                      &descriptor->super);
-            }
-        }
-    }));
+    // The ACTION argument of OPAL_THREAD_SCOPED_LOCK has to be
```
Comment (bwbarrett) [inline opal/mca/btl/base/btl_base_am_rdma.c:768]: Does it have to be a macro?  Or could you just have continuation characters in the definition?

**Review by bwbarrett — APPROVED** [review]

File: opal/mca/btl/base/btl_base_am_rdma.c (hunk 2 above)
Comment (bwbarrett) [reply opal/mca/btl/base/btl_base_am_rdma.c:768]: I agree that the macro style you propose looks cleaner.  But either way, I think your comment over-states things a bit.

**Review by abouteiller — APPROVED** [review]
thanks for fixing these printfs

File: ompi/mca/coll/ftagree/coll_ftagree_earlyreturning.c (hunk 1 above)
Comment (jsquyres) [reply ompi/mca/coll/ftagree/coll_ftagree_earlyreturning.c:3238]: Actually, digging deeper, I see in the description of `opal_snprintf` in at https://github.com/open-mpi/ompi/blob/651be3974d3029cfd387d87070f62ea6072c08a9/opal/util/printf.h#L52

We *do* actually have a `#define snprintf opal_snprintf` in `opal_config_bottom.h`, but only in the case where the compiler does not provide `opal_snprintf` https://github.com/open-mpi/ompi/blob/651be3974d3029cfd387d87070f62ea6072c08a9/opal/include/opal_config_bottom.h#L381-L383

It looks like `opal_config_bottom.h` has been this way since Open MPI v1.1.x (i.e., pretty much the very beginning).

If we think we should be using `opal_snprintf()` everywhere, should we make this `#define` be unconditional (i.e., _always_ define `snprintf` to be `opal_snprintf`)?

I only see 3 other places in the OMPI code base where we actually use `opal_snprintf`, and they all have Jeff-like comments saying "We're using opal_snprintf() to avoid a stupid compiler warning."

Comment (bwbarrett) [reply ompi/mca/coll/ftagree/coll_ftagree_earlyreturning.c:3238]: Ah, fair enough.  We're really inconsistent on when the opal_<function> calls are mandatory or not.  I actually dislike them, but we do mandate them in some situations (like opal_asprintf).  I really dislike this work around for the compiler warning; I wonder if we wouldn't be better off just disabling that warning?

**Comment by jsquyres** [comment]
@bwbarrett I rolled back previous `opal_snprintf()` changes (to `MPI_TYPE_CREATE_F90_*` routines) and added `-Wformat-truncation=0`.

**Review by bwbarrett — APPROVED** [review]
