### PR TITLE
Resolve Coverity problems reported in issue #9705

### LINKED ISSUE #9705: Coverity/static analysis issues with TCP interface code
@drwootton @jjhursey Looks like we got some static analysis problems from 0b37cd2e9dacf4c2aadafeb626365ec314181a9c (PR #9681).  Can you fix?

Thanks!

```
________________________________________________________________________________________________________
*** CID 1494436:  Null pointer dereferences  (FORWARD_NULL)
/opal/mca/btl/tcp/btl_tcp_component.c: 758 in split_and_resolve()
752             }
753     
754             free(tmp);
755         }
756     
757         /* Mark the end of the interface name array with NULL */
   CID 1494436:  Null pointer dereferences  (FORWARD_NULL)
   Dereferencing null pointer "interfaces".
758         interfaces[interface_count] = NULL;
759         free(argv);
760         free(*orig_str);
761         *orig_str = opal_argv_join(interfaces, ',');
762         return interfaces;
763     }
```

```
** CID 1494435:    (RESOURCE_LEAK)
/opal/mca/btl/tcp/btl_tcp_component.c: 676 in split_and_resolve()
/opal/mca/btl/tcp/btl_tcp_component.c: 738 in split_and_resolve()
________________________________________________________________________________________________________
*** CID 1494435:    (RESOURCE_LEAK)
/opal/mca/btl/tcp/btl_tcp_component.c: 676 in split_and_resolve()
670                     }
671                 }
672                 if (n == interface_count) {
673                     opal_output_verbose(20,
674                                         opal_btl_base_framework.framework_output,
675                                         "btl: tcp: Using interface: %s ", argv[i]);
   CID 1494435:    (RESOURCE_LEAK)
   Failing to save or free storage allocated by "strdup(argv[i])" leaks it.
676                     opal_argv_append(&interface_count, &interfaces, strdup(argv[i]));
677                 }
678                 continue;
679             }
680     
681             /* Found a subnet notation.  Convert it to an IP
/opal/mca/btl/tcp/btl_tcp_component.c: 738 in split_and_resolve()
732                     if (n == interface_count) {
733                         opal_output_verbose(20,
734                                             opal_btl_base_framework.framework_output,
735                                             "btl: tcp: Found match: %s (%s)",
736                                             opal_net_get_hostname((struct sockaddr*) &if_inaddr),
737                                             if_name);
   CID 1494435:    (RESOURCE_LEAK)
   Failing to save or free storage allocated by "strdup(if_name)" leaks it.
738                         opal_argv_append(&interface_count, &interfaces, strdup(if_name));
739                     }
740                 }
741             }
742     
743             /* If we didn't find a match, keep trying */
```

### PR DESCRIPTION
**Pull request by drwootton**
Eliminate redundant use of strdup in call to opal_argv_append, check for possible null pointer following end of main loop in split_and_resolve.

The Coverity CID numbers resolved by this pull request are
CID 1494435
CID 1494436

This resolves issue #9705 

Signed-off-by: David Wootton <dwootton@us.ibm.com>

### CODE REVIEW

**Comment by bwbarrett** [comment]
ok to test

File: opal/mca/btl/tcp/btl_tcp_component.c [hunk 1]
```diff
@@ -735,7 +735,7 @@ static char **split_and_resolve(char **orig_str, char *name, bool reqd)
                                         "btl: tcp: Found match: %s (%s)",
                                         opal_net_get_hostname((struct sockaddr*) &if_inaddr),
                                         if_name);
-                    opal_argv_append(&interface_count, &interfaces, strdup(if_name));
```
Comment (jjhursey) [inline opal/mca/btl/tcp/btl_tcp_component.c:738]: Fixes Coverity 1494435 - the `if_name` is a stack variable for this function. The problem was that the `strdup` of the value was lost because `opal_argv_append` also does a `strdup`.

**Review by jjhursey — APPROVED** [review]
Thanks for cleaning up those coverity issues!

**Comment by jjhursey** [comment]
@jsquyres Can you take a quick look at this PR as a second set of eyes? Since you also reviewed https://github.com/open-mpi/ompi/pull/9681
Thanks!

**Review by jsquyres — APPROVED** [review]
Nit: can we amend the commit message to include the CID numbers that were fixed?  Thanks!

**Comment by jjhursey** [comment]
Commit message has been updated to include the coverity IDs.

**Comment by jjhursey** [comment]
@drwootton Can you cherry-pick PR #9681 and this (in a single PR) to the v5.0.x and v4.1.x branches? Thanks!
