### PR TITLE
btl/uct: fix deadlock in connection code

### LINKED ISSUE #5820: btl/uct: hang in endpoint connection with multithreaded with IB.
@hjelmn I worked in btl/uct and bumped into this problem where in the endpoint connect stage. If we have more than 1 context, it has this race condition where everyone is trying to create the endpoint. I understand that ugni does not have this problem as you can connect directly to the interface.

I printed out several steps below, the application is ping-ping with 2 threads on each side.

rank 0:
```
[a01.alembert:35166] got connection request for endpoint 0xa3c0e0. length = 28
[a01.alembert:35166] got connection request for endpoint 0xa3c0e0. length = 24
[a01.alembert:35166] ep 0xa3c0e0 is now ready...
[a01.alembert:35166] mca: bml: Using uct btl for send to [[36789,1],1] on node a02
[a01.alembert:35166] got connection request for endpoint 0xa3c0e0. length = 28
[a01.alembert:35166] got connection request for endpoint 0xa3c0e0. length = 28
[a01.alembert:35166] got connection request for endpoint 0xa3c0e0. length = 24
[a01.alembert:35166] ep 0xa3c0e0 is now ready...

[a01.alembert:35166] ep 0xa3c0e0 is not ready for frag 0xa7f600
```
In rank 0, we can see that the endpoint is marked as ready twice but failed to send. This might be a race condition. I understand that if the frag is not ready, it gets put into `pending_frags` list and will get marked ready once endpoint becomes available but the endpoint is already available. So we have a frag stuck in the list?

rank 1:
```
[a02.alembert:30092] got connection request for endpoint 0xa3b990. length = 28
[a02.alembert:30092] ep 0xa3b990 is not ready for frag 0xa731c0
[a02.alembert:30092] got connection request for endpoint 0xa3b990. length = 24
[a02.alembert:30092] ep 0xa3b990 is now ready...
[a02.alembert:30092] marking frag 0xa731c0 ready
[a02.alembert:30092] progress_pending: frag 0xa731c0 has become ready, sending...
[a02.alembert:30092] ep 0xa3b990 is not ready for frag 0xa731c0
[a02.alembert:30092] ep 0xa3b990 is not ready for frag 0xa73040
[a02.alembert:30092] got connection request for endpoint 0xa3b990. length = 28
[a02.alembert:30092] got connection request for endpoint 0xa3b990. length = 24
[a02.alembert:30092] ep 0xa3b990 is now ready...
[a02.alembert:30092] marking frag 0xa73040 ready
[a02.alembert:30092] progress_pending: frag 0xa73040 has become ready, sending...
[a02.alembert:30092] got connection request for endpoint 0xa3b990. length = 24
[a02.alembert:30092] got connection request for endpoint 0xa3b990. length = 28
```
In rank 1, it seems to be fine. The frag is marked ready and sent.

I create this issue as a tracker. I am currently working on debugging this but hope that you might be able to suggest me so I can look into the right direction.

### LINKED ISSUE #5821: btl/uct: zcopy error with IB on large message.
The issue can be reproduced with any multithreaded communication with message size bigger than 64k.

```
[1538489194.112583] [a01:35024:1]    rc_verbs_ep.c:344  UCX  ERROR Invalid am_zcopy payload length: 65544 (expected: <=8192)
[1538489194.112590] [a01:35024:1]    rc_verbs_ep.c:344  UCX  ERROR Invalid am_zcopy payload length: 65544 (expected: <=8192)
[1538489194.112598] [a01:35024:1]    rc_verbs_ep.c:344  UCX  ERROR Invalid am_zcopy payload length: 65544 (expected: <=8192)
[1538489194.112605] [a01:35024:1]    rc_verbs_ep.c:344  UCX  ERROR Invalid am_zcopy payload length: 65544 (expected: <=8192)
```

I can reproduce this on my benchmark and also multithreaded chemistry application (MADNESS). We only have one `uct_am_zcopy` call in the BTL and it is here.

```c
  if (NULL != frag->base.super.registration) {
152             frag->comp.dev_context = context;
153
154             ucs_status = uct_ep_am_zcopy (ep_handle, MCA_BTL_UCT_FRAG, &frag->header, sizeof (frag->header),
155                                           &frag->uct_iov, 1, 0, &frag->comp.uct_comp);
156         } else {
157             /* short message */
158             /* restore original flags */
159             frag->base.des_flags = flags;
160
161             if (1 == frag->base.des_segment_count) {
162                 ucs_status = uct_ep_am_short (ep_handle, MCA_BTL_UCT_FRAG, frag->header.value, frag->uct_iov.buffer,
163                                               frag->uct_iov.length);
164             } else {
165                 ucs_status = uct_ep_am_bcopy (ep_handle, MCA_BTL_UCT_FRAG, mca_btl_uct_send_frag_pack, frag, 0);
166             }
167         }
```

I put `assert(frag->uct_iov.length <= 8192)` and it trips there. I have not tracked this problem down yet but create this issue as a tracker instead.

### PR DESCRIPTION
**Pull request by hjelmn**
This commit fixes a deadlock that can occur when using a TL that
supports the connect to endpoint model. The deadlock was occurring
while processing an incoming connection requests. This was done from
an active-message callback. For some unknown reason (at this time)
this callback was sometimes hanging. To avoid the issue the connection
active-message is saved for later processing.

At the same time I cleaned up the connection code to eliminate
duplicate messages when possible.

Closes #5820
Closes #5821

Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by hjelmn** [comment]
@thananon Please test. I can't reproduce the issue with these changes.

**Comment by thananon** [comment]
did a new commit just fix that connection reqs typo or there's more? Do I have to re-cherrypick?

**Comment by hjelmn** [comment]
Yeah, just fixed it. Was hoping to catch it before you grabbed it.

**Comment by hjelmn** [comment]
Heh, pml/ob1 + btl/ucx now beats pml/ucx in the (bad but interesting) thread-tests-1.1 tests on aarch64:

```
mpirun --mca btl ^openib --mca btl_base_verbose 0 --mca pml ucx -n 2 -N 1 --bind-to none ./message_rate_th 32
Thread 0, message rate 984.465353 messages/sec
Thread 8, message rate 884.796744 messages/sec
Thread 23, message rate 586.044601 messages/sec
Thread 27, message rate 559.219452 messages/sec
Thread 29, message rate 552.045250 messages/sec
Thread 2, message rate 509.109080 messages/sec
Thread 6, message rate 493.508727 messages/sec
Thread 4, message rate 490.550874 messages/sec
Thread 17, message rate 484.756934 messages/sec
Thread 10, message rate 468.280035 messages/sec
Thread 16, message rate 433.960365 messages/sec
Thread 18, message rate 351.193747 messages/sec
Thread 25, message rate 348.311123 messages/sec
Thread 21, message rate 343.757082 messages/sec
Thread 20, message rate 340.415010 messages/sec
Thread 15, message rate 326.256207 messages/sec
Thread 22, message rate 322.170270 messages/sec
Thread 14, message rate 309.701402 messages/sec
Thread 26, message rate 308.021233 messages/sec
Thread 31, message rate 295.131333 messages/sec
Thread 11, message rate 286.492896 messages/sec
Thread 13, message rate 281.397824 messages/sec
Thread 19, message rate 279.630941 messages/sec
Thread 7, message rate 265.525070 messages/sec
Thread 9, message rate 256.796376 messages/sec
Thread 1, message rate 246.550197 messages/sec
Thread 28, message rate 246.312438 messages/sec
Thread 30, message rate 246.170871 messages/sec
Thread 24, message rate 245.829274 messages/sec
Thread 5, message rate 245.621062 messages/sec
Thread 12, message rate 245.602132 messages/sec
Thread 3, message rate 245.570761 messages/sec
```

```
mpirun --mca btl_uct_num_contexts_per_module 64 --mca btl_base_verbose 0 --mca pml ob1 --mca btl self,vader,uct --mca btl_uct_memory_domains ib/mlx5_0,ib/mlx5_3 -n 2 -N 1 --bind-to none ./message_rate_th 32
Thread 2, message rate 2016.618043 messages/sec
Thread 7, message rate 1973.630367 messages/sec
Thread 3, message rate 1972.028961 messages/sec
Thread 4, message rate 1971.934388 messages/sec
Thread 24, message rate 1972.755685 messages/sec
Thread 6, message rate 1970.364943 messages/sec
Thread 14, message rate 1970.760161 messages/sec
Thread 8, message rate 1970.227133 messages/sec
Thread 18, message rate 1970.728087 messages/sec
Thread 16, message rate 1970.573566 messages/sec
Thread 20, message rate 1970.637034 messages/sec
Thread 21, message rate 1970.556082 messages/sec
Thread 9, message rate 1969.778026 messages/sec
Thread 28, message rate 1970.724667 messages/sec
Thread 15, message rate 1970.076312 messages/sec
Thread 0, message rate 1969.311326 messages/sec
Thread 1, message rate 1960.177859 messages/sec
Thread 12, message rate 1960.682545 messages/sec
Thread 10, message rate 1960.482754 messages/sec
Thread 11, message rate 1960.644151 messages/sec
Thread 19, message rate 1960.995651 messages/sec
Thread 26, message rate 1961.302117 messages/sec
Thread 13, message rate 1960.717056 messages/sec
Thread 23, message rate 1961.157769 messages/sec
Thread 5, message rate 1960.284529 messages/sec
Thread 29, message rate 1961.424369 messages/sec
Thread 22, message rate 1961.044944 messages/sec
Thread 30, message rate 1961.504949 messages/sec
Thread 31, message rate 1961.480730 messages/sec
Thread 17, message rate 1960.878816 messages/sec
Thread 25, message rate 1961.079569 messages/sec
Thread 27, message rate 1961.087662 messages/sec
```

That was not expected.

**Comment by thananon** [comment]
> That was not expected.
I dont know about that.


Still have this problem. I will try a clean cherry-pick in the meantime.
```
✘ tpatinya@saturn  ~/multirate   master  mpirun -np 2 --map-by node --bind-to socket -mca btl_openib_allow_ib true  -mca pml ob1 -mca btl uct,self -mca btl_uct_memory_domains ib/mlx5_0 -mca btl_base_verbose 0   ./pairwise -s 71024 -c -w 100 -i 100 -t 10

mlx5: a08.alembert: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
0000000a 000000d7 00000000 00002028
00006216 0005d701 00034e2e 00640ce2
[a08:17496:0:17504] rc_verbs_common.h:188  UCX Fatal: receive completion[4] with error on mlx5_0/0x7fffb402a500: local length error, vendor_err 0xd7 wr_id 0x7fff9b333e35
mlx5: a05.alembert: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000004 00000000 00000000 00000000
00000000 00008a12 0a0357ef 00c8c9d2
[a05:13603:0:13616] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))

/home/tpatinya/Download/ucx/src/uct/ib/rc/verbs/rc_verbs_common.h: [ uct_rc_verbs_iface_poll_rx_common() ]
      ...
      185     }
      186
      187     UCT_IB_IFACE_VERBS_FOREACH_RXWQE(&iface->super, i, hdr, wc, num_wcs) {
==>   188         uct_ib_log_recv_completion(&iface->super, IBV_QPT_RC, &wc[i], hdr,
      189                                    wc[i].byte_len, uct_rc_verbs_common_packet_dump);
      190         uct_rc_verbs_iface_handle_am(iface, hdr, wc[i].wr_id, wc[i].qp_num,
      191                                      wc[i].byte_len, wc[i].imm_data, wc[i].slid);


/home/tpatinya/Download/ucx/src/ucs/datastruct/mpool.inl: [ ucs_mpool_obj_to_elem() ]
      ...
       59 static inline ucs_mpool_elem_t *ucs_mpool_obj_to_elem(void *obj)
       60 {
       61     ucs_mpool_elem_t *elem = (ucs_mpool_elem_t*)obj - 1;
==>    62     VALGRIND_MAKE_MEM_DEFINED(elem, sizeof *elem);
       63     return elem;
       64 }
       65

==== backtrace ====
 0 0x000000000002b515 uct_rc_verbs_iface_poll_rx_common()  /home/tpatinya/Download/ucx/src/uct/ib/rc/verbs/rc_verbs_common.h:188
 1 0x000000000002b515 uct_rc_verbs_iface_poll_rx_common()  /home/tpatinya/Download/ucx/src/uct/ib/rc/verbs/rc_verbs_common.h:198
 2 0x000000000002b515 uct_rc_verbs_iface_progress()  /home/tpatinya/Download/ucx/src/uct/ib/rc/verbs/rc_verbs_iface.c:111
 3 0x0000000000004d7a mca_btl_uct_tl_progress.isra.0.part.1()  btl_uct_component.c:0
 4 0x000000000000517b mca_btl_uct_component_progress()  btl_uct_component.c:0
 5 0x0000000000031dec opal_progress()  ???:0
 6 0x00000000000385b5 ompi_sync_wait_mt()  ???:0
 7 0x000000000004f87d ompi_request_default_wait_all()  ???:0
 8 0x0000000000095ccf MPI_Waitall()  ???:0
 9 0x0000000000401956 thread_work()  /home/tpatinya/multirate/pairwise.c:233
10 0x0000000000007e25 start_thread()  /usr/src/debug/glibc-2.17-c758a686/nptl/pthread_create.c:308
11 0x00000000000f834d __clone()  /usr/src/debug////////glibc-2.17-c758a686/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:113
===================
```

**Comment by hjelmn** [comment]
I am getting this though:

```
[cn828:77188] *** An error occurred in MPI_Irecv
[cn828:77188] *** reported by process [226754561,70368744177665]
[cn828:77188] *** on communicator MPI COMMUNICATOR 9 DUP FROM 0
[cn828:77188] *** MPI_ERR_INTERN: internal error
[cn828:77188] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[cn828:77188] ***    and potentially your MPI job)
```

Not sure what is causing that. Digging now.

**Comment by thananon** [comment]
That one, I know. I reported it a while back but there's no one looking into it. I think our Irecv is not so thread safe. Other MPI doesn't have this problem.

I just ignore that for now and just rerun until I get result.

**Comment by thananon** [comment]
Yeah #2921 
I dont remember closing the issue tho...

**Comment by hjelmn** [comment]
Found a couple more issue. Narrowing it down further....

**Comment by hjelmn** [comment]
I think the recv_req error is related. When I run your code with vader as the btl it runs fine every time. I will spend a little more time on this today then will pick it back up on monday.

**Comment by hjelmn** [comment]
Interesting. I wonder why vader is immune to it.

**Comment by hjelmn** [comment]
Found 3 bugs in the active message path in btl/uct. Now your code runs with 8 threads every time but hangs with 10. Will pick this back up next week.

**Comment by hjelmn** [comment]
Think I have identified the final issue. Should have the fixes up in this PR in a couple of hours.

**Comment by hjelmn** [comment]
Nope. From what I can see @ 10 (or even 20) threads one of the threads gets stuck. The sending side is in MPI_Recv after getting UCS_OK from sending all the outstanding fragments. The receive side is blocked waiting for at least 1 receive to complete. This suggests that the AM callback is not firing for all receives... Not sure what is going on. Going back to a known state then applying the 3 fixes again.

**Comment by hjelmn** [comment]
Now thinking I messed up my branch. I applied the patches to a clean version of this branch and it appears to be running ok. Will test more tomorrow and update this branch with what I have so far.

**Comment by hjelmn** [comment]
@thananon I think I know why the irecv error happens. Testing a fix now.

**Comment by thananon** [comment]
Thank you for looking into this Nathan. I really appreciate it.
Also I'm curious to know what went wrong as well.

**Comment by hjelmn** [comment]
@thananon Ok, with this and the #5922 you should be good to go. Let me know if you run into any more issues.

File: opal/mca/btl/uct/btl_uct_device_context.h [hunk 1]
```diff
@@ -91,13 +91,12 @@ mca_btl_uct_module_get_tl_context_specific (mca_btl_uct_module_t *module, mca_bt
     if (OPAL_UNLIKELY(NULL == context)) {
         mca_btl_uct_device_context_t *new_context;
```
Comment (thananon) [inline opal/mca/btl/uct/btl_uct_device_context.h]: This `new_context` became unused and compiler is complaining.

Comment (thananon) [reply opal/mca/btl/uct/btl_uct_device_context.h]: also in `module.c:77` rdma_tl is unused.

**Comment by hjelmn** [comment]
Alright. Will fix those and one other deep recursion bug (progress from get) then this is good to go.

**Comment by hjelmn** [comment]
@thananon Ok. Finished. Give the final version a try when you get a chance.
