### PR TITLE
Fix patcher for ppc and aarch64

### LINKED ISSUE #13014: OPAL_PATCHER_BEGIN/OPAL_PATCHER_END is broken in some cases
Forwarded from https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95692 :
https://github.com/open-mpi/ompi/blob/0bccfcdf17dc10b0c9c4b7090fe8825d899ac3d8/opal/mca/patcher/patcher.h#L31

The inline-asm needs to clobber memory to avoid moving the END before a different restore the r2.

That is BEGIN should be:

    asm volatile ("std 2, %0" : "=m" (toc_save) :: "memory");
    asm volatile ("nop; nop; nop; nop; nop" ::: "memory");;

While END should be:

    asm volatile ("ld  2, %0" : : "m" (toc_save) : "memory");;

### PR DESCRIPTION
**Pull request by bosilca**
Prevent the compiler from reordering the instructions in the patcher by marking the assembly code as clobbering memory.

Thanks @pinskia for the patch and for bringing the discussion on the gcc bugzilla.

I was not able to test this. The code generated by [godbolt](https://godbolt.org/) seems legit, but I did not yet figured out how to look at the disassembled code in OMPI.

Fixes #13014.

### CODE REVIEW

File: opal/mca/patcher/patcher.h [hunk 1]
```diff
@@ -30,9 +30,9 @@
  * Reference: "64-bit PowerPC ELF Application Binary Interface Supplement 1.9" */
 #    define OPAL_PATCHER_BEGIN                      \
         unsigned long toc_save;                     \
-        asm volatile("std 2, %0" : "=m"(toc_save)); \
-        asm volatile("nop; nop; nop; nop; nop");
-#    define OPAL_PATCHER_END asm volatile("ld  2, %0" : : "m"(toc_save));
+        asm volatile("std 2, %0" : "=m"(toc_save) :: "memory"); \
```
Comment (devreal) [inline opal/mca/patcher/patcher.h:33]: Should we add a reference to the GCC ticket to remember why we globber the memory here? Just in case someone looks at this in 3 years from now and tries to save some cycles...

Comment (janjust) [reply opal/mca/patcher/patcher.h:33]: @bosilca ^

**Review by devreal — APPROVED** [review]

File: opal/mca/patcher/patcher.h (hunk 1 above)
Comment (bosilca) [reply opal/mca/patcher/patcher.h:33]: dang, I wanted to add this link to the commit. Sorry.
