### PR TITLE
Avoid static initialization of recursive mutexes

### LINKED ISSUE #12029: [openmpi 5.0] `error: 'OPAL_RECURSIVE_MUTEX_STATIC_INIT' undeclared here (not in a function); did you mean 'OPAL_MUTEX_STATIC_INIT'?`
Something is not right here:
```
  CC       instance/instance.lo
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_openmpi/openmpi-gcc13/work/openmpi-5.0.0/ompi/instance/instance.c:62:47: error: 'OPAL_RECURSIVE_MUTEX_STATIC_INIT' undeclared here (not in a function); did you mean 'OPAL_MUTEX_STATIC_INIT'?
   62 | static opal_recursive_mutex_t instance_lock = OPAL_RECURSIVE_MUTEX_STATIC_INIT;
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                               OPAL_MUTEX_STATIC_INIT
make[2]: *** [instance/instance.lo] Error 1
```

@shintaro-iwasaki Could this be related to https://github.com/open-mpi/ompi/commit/bcd376a1158b0960746e592080e430446b5f2218 commit?

### PR DESCRIPTION
**Pull request by bosilca**
There is no portable way to statically initialize recursive mutexes. Where possible avoid doing so, and where not possible add a specialized __constructor__ (thanks @eschnett for the patch).

Fixes #12029.

### CODE REVIEW

File: ompi/instance/instance.c [hunk 1]
```diff
@@ -59,7 +59,14 @@
 
 ompi_predefined_instance_t ompi_mpi_instance_null = {{{{0}}}};
 
+#if defined(OPAL_RECURSIVE_MUTEX_STATIC_INIT)
 static opal_recursive_mutex_t instance_lock = OPAL_RECURSIVE_MUTEX_STATIC_INIT;
+#else
+static opal_recursive_mutex_t instance_lock;
+__attribute__((__constructor__)) static void instance_lock_init(void) {
```
Comment (devreal) [inline ompi/instance/instance.c:66]: The `constructor` attribute isn't part of the C standard so we should check if it is actually available. What do we do if it isn't?

Comment (bosilca) [reply ompi/instance/instance.c]: All platforms supporting `PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP` or `PTHREAD_RECURSIVE_MUTEX_INITIALIZER` remain covered as before. The ones where they are not defined but where we have __constructor__ will be now covered. For the rest of them, one could argue that we could provide support for `.init` but that would be more than what I'm willing to invest in this.

There is a single instance of a statically initialized recursive mutex. It is not clear to me why the instance code needs a recursive mutex, but I'm not going to dig deeper.

**Review by devreal — APPROVED** [review]

File: opal/mca/btl/usnic/btl_usnic_component.c [hunk 2]
```diff
@@ -83,7 +83,7 @@
 #define OPAL_BTL_USNIC_NUM_COMPLETIONS 500
 
 /* MPI_THREAD_MULTIPLE_SUPPORT */
-opal_recursive_mutex_t btl_usnic_lock = OPAL_RECURSIVE_MUTEX_STATIC_INIT;
+opal_recursive_mutex_t btl_usnic_lock;  /* recursive mutexes must be dynamically initialized */
```
Comment (jsquyres) [inline opal/mca/btl/usnic/btl_usnic_component.c:86]: I'm not sure I understand this change -- does it need something like what you did in ompi/instance/instance.c?

Comment (devreal) [reply opal/mca/btl/usnic/btl_usnic_component.c:86]: The lock is initialized during component initialization: https://github.com/open-mpi/ompi/blob/787dd7bf65b3e8f5ebb0a64b455415e549364abe/opal/mca/btl/usnic/btl_usnic_component.c#L590

Comment (jsquyres) [reply opal/mca/btl/usnic/btl_usnic_component.c:86]: Ah, ok.  👍

Comment (bosilca) [reply opal/mca/btl/usnic/btl_usnic_component.c:86]: Correct. All components have a natural constructor, aka. their _init function, and no other function from the component can be used before it successfully returns. usnic BTL is correctly constructing the mutex in the _init, the static initialization was superfluous.

Unfortunately the same is not true for`instance`, I did not see an obvious initialization point inside the `instance.c` file. I imagine we could do something in one of the MPI initialization functions, but then we would need to either expose the recursive mutex, or expose an initializer for the `instances`.

**Comment by jsquyres** [comment]
@bosilca Ok to merge and cherry pick to v5.0.x?
