### PR TITLE
Attributes: replace custom void* union with C union

### LINKED ISSUE #10339: attribute functions lead to application segfault
Your attributes implementation is broken by GCC 11.

I speculate the code that GCC 11 has optimized into badness is not valid C, but I'm not enough of a language lawyer to know for sure.

# The Bug
```
$ /tmp/install-ompi-main/bin/mpicc -g3 MCVE.c
$ /tmp/install-ompi-main/bin/mpirun -n 1 gdb ./a.out -ex "set width 1000" -ex "thread apply all bt" -ex run -ex bt -ex "set confirm off" -ex quit
No protocol specified
...
Reading symbols from ./a.out...
Starting program: /tmp/armci-mpi-ompi-main/a.out
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7596700 (LWP 759692)]

Thread 1 "a.out" received signal SIGSEGV, Segmentation fault.
0x00005555555552ed in main () at MCVE.c:19
19	      if ( (*attr_val)==MPI_WIN_SEPARATE ) {
#0  0x00005555555552ed in main () at MCVE.c:19
```

# MCVE
```c
#include <stdio.h>
#include <mpi.h>

int main(void)
{
  int world_me;
  MPI_Win win;
  void * base;
  void * attr_ptr;
  int    attr_flag;
  MPI_Init(NULL,NULL);
  MPI_Comm_rank(MPI_COMM_WORLD, &world_me);
  MPI_Win_allocate( 1, 1, MPI_INFO_NULL, MPI_COMM_WORLD, &base, &win);
  /* this function will always return flag=false in MPI-2 */
  MPI_Win_get_attr(win, MPI_WIN_MODEL, &attr_ptr, &attr_flag);
  if (attr_flag) {
    int * attr_val = (int*)attr_ptr;
    if (world_me==0) {
      if ( (*attr_val)==MPI_WIN_SEPARATE ) {
        printf("MPI_WIN_MODEL = MPI_WIN_SEPARATE \n" );
      } else if ( (*attr_val)==MPI_WIN_UNIFIED ) {
        printf("MPI_WIN_MODEL = MPI_WIN_UNIFIED \n" );
      } else {
        printf("MPI_WIN_MODEL = %d (not UNIFIED or SEPARATE) \n", *attr_val );
      }
    }
  } else {
    if (world_me==0) {
      printf("MPI_WIN_MODEL attribute missing \n");
    }
  }
  MPI_Win_free(&win);
  MPI_Finalize();
  return 0;
}
```

# ompi_info
```
jhammond@nuclear:/tmp/armci-mpi-ompi-main$ /tmp/install-ompi-main/bin/ompi_info
                 Package: Open MPI jhammond@nuclear Distribution
                Open MPI: 5.1.0a1
  Open MPI repo revision: v2.x-dev-9819-g02d91b56b8
   Open MPI release date: Unreleased developer copy
                 MPI API: 3.1.0
            Ident string: 5.1.0a1
                  Prefix: /tmp/install-ompi-main
 Configured architecture: x86_64-pc-linux-gnu
           Configured by: jhammond
           Configured on: Fri Apr 29 07:49:20 UTC 2022
          Configure host: nuclear
  Configure command line: '--prefix=/tmp/install-ompi-main' '--without-psm2'
                          '--without-cuda' '--without-ofi'
                          '--without-libfabric'
                Built by: jhammond
                Built on: Fri 29 Apr 2022 07:52:53 AM UTC
              Built host: nuclear
              C bindings: yes
             Fort mpif.h: yes (all)
            Fort use mpi: yes (full: ignore TKR)
       Fort use mpi size: deprecated-ompi-info-value
        Fort use mpi_f08: yes
 Fort mpi_f08 compliance: The mpi_f08 module is available, but due to
                          limitations in the gfortran compiler and/or Open
                          MPI, does not support the following: array
                          subsections, direct passthru (where possible) to
                          underlying Open MPI's C functionality
  Fort mpi_f08 subarrays: no
           Java bindings: no
  Wrapper compiler rpath: runpath
              C compiler: gcc
     C compiler absolute: /bin/gcc
  C compiler family name: GNU
      C compiler version: 11.1.0
            C++ compiler: g++
   C++ compiler absolute: /bin/g++
           Fort compiler: gfortran
       Fort compiler abs: /bin/gfortran
         Fort ignore TKR: yes (!GCC$ ATTRIBUTES NO_ARG_CHECK ::)
   Fort 08 assumed shape: yes
      Fort optional args: yes
          Fort INTERFACE: yes
    Fort ISO_FORTRAN_ENV: yes
       Fort STORAGE_SIZE: yes
      Fort BIND(C) (all): yes
      Fort ISO_C_BINDING: yes
 Fort SUBROUTINE BIND(C): yes
       Fort TYPE,BIND(C): yes
 Fort T,BIND(C,name="a"): yes
            Fort PRIVATE: yes
           Fort ABSTRACT: yes
       Fort ASYNCHRONOUS: yes
          Fort PROCEDURE: yes
         Fort USE...ONLY: yes
           Fort C_FUNLOC: yes
 Fort f08 using wrappers: yes
         Fort MPI_SIZEOF: yes
             C profiling: yes
   Fort mpif.h profiling: yes
  Fort use mpi profiling: yes
   Fort use mpi_f08 prof: yes
          Thread support: posix (MPI_THREAD_MULTIPLE: yes, OPAL support: yes,
                          OMPI progress: no, Event lib: yes)
           Sparse Groups: no
  Internal debug support: no
  MPI interface warnings: yes
     MPI parameter check: runtime
Memory profiling support: no
Memory debugging support: no
              dl support: yes
   Heterogeneous support: no
       MPI_WTIME support: native
     Symbol vis. support: yes
   Host topology support: yes
            IPv6 support: no
          MPI extensions: affinity, cuda, ftmpi
 Fault Tolerance support: yes
          FT MPI support: yes
  MPI_MAX_PROCESSOR_NAME: 256
    MPI_MAX_ERROR_STRING: 256
     MPI_MAX_OBJECT_NAME: 64
        MPI_MAX_INFO_KEY: 36
        MPI_MAX_INFO_VAL: 256
       MPI_MAX_PORT_NAME: 1024
  MPI_MAX_DATAREP_STRING: 128
           MCA allocator: basic (MCA v2.1.0, API v2.0.0, Component v5.1.0)
           MCA allocator: bucket (MCA v2.1.0, API v2.0.0, Component v5.1.0)
           MCA backtrace: execinfo (MCA v2.1.0, API v2.0.0, Component v5.1.0)
                 MCA btl: self (MCA v2.1.0, API v3.3.0, Component v5.1.0)
                 MCA btl: sm (MCA v2.1.0, API v3.3.0, Component v5.1.0)
                 MCA btl: tcp (MCA v2.1.0, API v3.3.0, Component v5.1.0)
                  MCA dl: dlopen (MCA v2.1.0, API v1.0.0, Component v5.1.0)
                  MCA if: linux_ipv6 (MCA v2.1.0, API v2.0.0, Component
                          v5.1.0)
                  MCA if: posix_ipv4 (MCA v2.1.0, API v2.0.0, Component
                          v5.1.0)
         MCA installdirs: env (MCA v2.1.0, API v2.0.0, Component v5.1.0)
         MCA installdirs: config (MCA v2.1.0, API v2.0.0, Component v5.1.0)
              MCA memory: patcher (MCA v2.1.0, API v2.0.0, Component v5.1.0)
               MCA mpool: hugepage (MCA v2.1.0, API v3.1.0, Component v5.1.0)
             MCA patcher: overwrite (MCA v2.1.0, API v1.0.0, Component
                          v5.1.0)
              MCA rcache: grdma (MCA v2.1.0, API v3.3.0, Component v5.1.0)
           MCA reachable: weighted (MCA v2.1.0, API v2.0.0, Component v5.1.0)
               MCA shmem: mmap (MCA v2.1.0, API v2.0.0, Component v5.1.0)
               MCA shmem: posix (MCA v2.1.0, API v2.0.0, Component v5.1.0)
               MCA shmem: sysv (MCA v2.1.0, API v2.0.0, Component v5.1.0)
                MCA smsc: cma (MCA v2.1.0, API v1.0.0, Component v5.1.0)
             MCA threads: pthreads (MCA v2.1.0, API v1.0.0, Component v5.1.0)
               MCA timer: linux (MCA v2.1.0, API v2.0.0, Component v5.1.0)
                 MCA bml: r2 (MCA v2.1.0, API v2.1.0, Component v5.1.0)
                MCA coll: adapt (MCA v2.1.0, API v2.4.0, Component v5.1.0)
                MCA coll: basic (MCA v2.1.0, API v2.4.0, Component v5.1.0)
                MCA coll: han (MCA v2.1.0, API v2.4.0, Component v5.1.0)
                MCA coll: inter (MCA v2.1.0, API v2.4.0, Component v5.1.0)
                MCA coll: libnbc (MCA v2.1.0, API v2.4.0, Component v5.1.0)
                MCA coll: self (MCA v2.1.0, API v2.4.0, Component v5.1.0)
                MCA coll: sm (MCA v2.1.0, API v2.4.0, Component v5.1.0)
                MCA coll: sync (MCA v2.1.0, API v2.4.0, Component v5.1.0)
                MCA coll: tuned (MCA v2.1.0, API v2.4.0, Component v5.1.0)
                MCA coll: ftagree (MCA v2.1.0, API v2.4.0, Component v5.1.0)
                MCA fbtl: posix (MCA v2.1.0, API v2.0.0, Component v5.1.0)
               MCA fcoll: dynamic (MCA v2.1.0, API v2.0.0, Component v5.1.0)
               MCA fcoll: dynamic_gen2 (MCA v2.1.0, API v2.0.0, Component
                          v5.1.0)
               MCA fcoll: individual (MCA v2.1.0, API v2.0.0, Component
                          v5.1.0)
               MCA fcoll: vulcan (MCA v2.1.0, API v2.0.0, Component v5.1.0)
                  MCA fs: ufs (MCA v2.1.0, API v2.0.0, Component v5.1.0)
                MCA hook: comm_method (MCA v2.1.0, API v1.0.0, Component
                          v5.1.0)
                  MCA io: ompio (MCA v2.1.0, API v2.0.0, Component v5.1.0)
                 MCA osc: sm (MCA v2.1.0, API v3.0.0, Component v5.1.0)
                 MCA osc: rdma (MCA v2.1.0, API v3.0.0, Component v5.1.0)
                MCA part: persist (MCA v2.1.0, API v4.0.0, Component v5.1.0)
                 MCA pml: cm (MCA v2.1.0, API v2.1.0, Component v5.1.0)
                 MCA pml: ob1 (MCA v2.1.0, API v2.1.0, Component v5.1.0)
                 MCA pml: v (MCA v2.1.0, API v2.1.0, Component v5.1.0)
            MCA sharedfp: individual (MCA v2.1.0, API v2.0.0, Component
                          v5.1.0)
            MCA sharedfp: lockedfile (MCA v2.1.0, API v2.0.0, Component
                          v5.1.0)
            MCA sharedfp: sm (MCA v2.1.0, API v2.0.0, Component v5.1.0)
                MCA topo: basic (MCA v2.1.0, API v2.2.0, Component v5.1.0)
                MCA topo: treematch (MCA v2.1.0, API v2.2.0, Component
                          v5.1.0)
           MCA vprotocol: pessimist (MCA v2.1.0, API v2.0.0, Component
                          v5.1.0)
```

# It works with Open-MPI 3...

This code has worked for approximately 8 years with every other MPI implementation I've tried, including this one.
```
$ mpicc -g MCVE.c
$ mpirun -n 1 ./a.out
MPI_WIN_MODEL = MPI_WIN_UNIFIED
$ ompi_info
                 Package: Open MPI qa@sky1 Distribution
                Open MPI: 3.1.5
  Open MPI repo revision: v3.1.5
   Open MPI release date: Nov 15, 2019
                Open RTE: 3.1.5
  Open RTE repo revision: v3.1.5
   Open RTE release date: Nov 15, 2019
                    OPAL: 3.1.5
      OPAL repo revision: v3.1.5
       OPAL release date: Nov 15, 2019
                 MPI API: 3.1.0
            Ident string: 3.1.5
                  Prefix: /opt/nvidia/hpc_sdk/Linux_x86_64/22.2/comm_libs/openmpi/openmpi-3.1.5
 Configured architecture: x86_64-unknown-linux-gnu
          Configure host: sky1
           Configured by: qa
           Configured on: Thu Jan 13 10:48:36 PST 2022
          Configure host: sky1
  Configure command line: '--prefix=/proj/nv/libraries/Linux_x86_64/22.2/openmpi/209518-rel-1'
                          '--enable-shared' '--enable-static' '--without-tm'
                          '--enable-mpi-cxx' '--disable-wrapper-runpath'
                          '--without-ucx' '--without-libnl'
                          '--with-wrapper-ldflags=-Wl,-rpath
                          -Wl,$ORIGIN:$ORIGIN/../../lib:$ORIGIN/../../../lib:$ORIGIN/../../../compilers/lib:$ORIGIN/../../../../compilers/lib:$ORIGIN/../../../../../compilers/lib'
                          '--enable-mpirun-prefix-by-default'
                          '--with-libevent=internal' '--with-slurm'
                          '--without-libnl'
                          '--with-cuda=/proj/cuda/10.0/Linux_x86_64'
                Built by: qa
                Built on: Thu Jan 13 11:05:27 PST 2022
              Built host: sky1
              C bindings: yes
            C++ bindings: yes
             Fort mpif.h: yes (all)
            Fort use mpi: yes (full: ignore TKR)
       Fort use mpi size: deprecated-ompi-info-value
        Fort use mpi_f08: yes
 Fort mpi_f08 compliance: The mpi_f08 module is available, but due to
                          limitations in the nvfortran -nomp compiler and/or
                          Open MPI, does not support the following: array
                          subsections, direct passthru (where possible) to
                          underlying Open MPI's C functionality
  Fort mpi_f08 subarrays: no
           Java bindings: no
  Wrapper compiler rpath: rpath
              C compiler: nvc -nomp
     C compiler absolute: /proj/nv/Linux_x86_64/209518-rel/compilers/bin/nvc
  C compiler family name: PGI
      C compiler version: 22.2-0
            C++ compiler: nvc++ -nomp
   C++ compiler absolute: /proj/nv/Linux_x86_64/209518-rel/compilers/bin/nvc++
           Fort compiler: nvfortran -nomp
       Fort compiler abs: /proj/nv/Linux_x86_64/209518-rel/compilers/bin/nvfortran
         Fort ignore TKR: yes (!DIR$ IGNORE_TKR)
   Fort 08 assumed shape: no
      Fort optional args: yes
          Fort INTERFACE: yes
    Fort ISO_FORTRAN_ENV: yes
       Fort STORAGE_SIZE: yes
      Fort BIND(C) (all): yes
      Fort ISO_C_BINDING: yes
 Fort SUBROUTINE BIND(C): yes
       Fort TYPE,BIND(C): yes
 Fort T,BIND(C,name="a"): yes
            Fort PRIVATE: yes
          Fort PROTECTED: yes
           Fort ABSTRACT: yes
       Fort ASYNCHRONOUS: yes
          Fort PROCEDURE: yes
         Fort USE...ONLY: yes
           Fort C_FUNLOC: yes
 Fort f08 using wrappers: yes
         Fort MPI_SIZEOF: yes
             C profiling: yes
           C++ profiling: yes
   Fort mpif.h profiling: yes
  Fort use mpi profiling: yes
   Fort use mpi_f08 prof: yes
          C++ exceptions: no
          Thread support: posix (MPI_THREAD_MULTIPLE: yes, OPAL support: yes,
                          OMPI progress: no, ORTE progress: yes, Event lib:
                          yes)
           Sparse Groups: no
  Internal debug support: no
  MPI interface warnings: yes
     MPI parameter check: runtime
Memory profiling support: no
Memory debugging support: no
              dl support: yes
   Heterogeneous support: no
 mpirun default --prefix: yes
       MPI_WTIME support: native
     Symbol vis. support: yes
   Host topology support: yes
          MPI extensions: affinity, cuda
   FT Checkpoint support: no (checkpoint thread: no)
   C/R Enabled Debugging: no
  MPI_MAX_PROCESSOR_NAME: 256
    MPI_MAX_ERROR_STRING: 256
     MPI_MAX_OBJECT_NAME: 64
        MPI_MAX_INFO_KEY: 36
        MPI_MAX_INFO_VAL: 256
       MPI_MAX_PORT_NAME: 1024
  MPI_MAX_DATAREP_STRING: 128
           MCA allocator: basic (MCA v2.1.0, API v2.0.0, Component v3.1.5)
           MCA allocator: bucket (MCA v2.1.0, API v2.0.0, Component v3.1.5)
           MCA backtrace: execinfo (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                 MCA btl: self (MCA v2.1.0, API v3.0.0, Component v3.1.5)
                 MCA btl: openib (MCA v2.1.0, API v3.0.0, Component v3.1.5)
                 MCA btl: smcuda (MCA v2.1.0, API v3.0.0, Component v3.1.5)
                 MCA btl: tcp (MCA v2.1.0, API v3.0.0, Component v3.1.5)
                 MCA btl: vader (MCA v2.1.0, API v3.0.0, Component v3.1.5)
            MCA compress: bzip (MCA v2.1.0, API v2.0.0, Component v3.1.5)
            MCA compress: gzip (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                 MCA crs: none (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                  MCA dl: dlopen (MCA v2.1.0, API v1.0.0, Component v3.1.5)
               MCA event: libevent2022 (MCA v2.1.0, API v2.0.0, Component
                          v3.1.5)
               MCA hwloc: hwloc1117 (MCA v2.1.0, API v2.0.0, Component
                          v3.1.5)
                  MCA if: linux_ipv6 (MCA v2.1.0, API v2.0.0, Component
                          v3.1.5)
                  MCA if: posix_ipv4 (MCA v2.1.0, API v2.0.0, Component
                          v3.1.5)
         MCA installdirs: env (MCA v2.1.0, API v2.0.0, Component v3.1.5)
         MCA installdirs: config (MCA v2.1.0, API v2.0.0, Component v3.1.5)
              MCA memory: patcher (MCA v2.1.0, API v2.0.0, Component v3.1.5)
               MCA mpool: hugepage (MCA v2.1.0, API v3.0.0, Component v3.1.5)
             MCA patcher: overwrite (MCA v2.1.0, API v1.0.0, Component
                          v3.1.5)
                MCA pmix: isolated (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                MCA pmix: pmix2x (MCA v2.1.0, API v2.0.0, Component v3.1.5)
               MCA pstat: linux (MCA v2.1.0, API v2.0.0, Component v3.1.5)
              MCA rcache: grdma (MCA v2.1.0, API v3.3.0, Component v3.1.5)
              MCA rcache: gpusm (MCA v2.1.0, API v3.3.0, Component v3.1.5)
              MCA rcache: rgpusm (MCA v2.1.0, API v3.3.0, Component v3.1.5)
           MCA reachable: weighted (MCA v2.1.0, API v2.0.0, Component v3.1.5)
               MCA shmem: mmap (MCA v2.1.0, API v2.0.0, Component v3.1.5)
               MCA shmem: posix (MCA v2.1.0, API v2.0.0, Component v3.1.5)
               MCA shmem: sysv (MCA v2.1.0, API v2.0.0, Component v3.1.5)
               MCA timer: linux (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                 MCA dfs: app (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                 MCA dfs: orted (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                 MCA dfs: test (MCA v2.1.0, API v1.0.0, Component v3.1.5)
              MCA errmgr: default_app (MCA v2.1.0, API v3.0.0, Component
                          v3.1.5)
              MCA errmgr: default_hnp (MCA v2.1.0, API v3.0.0, Component
                          v3.1.5)
              MCA errmgr: default_orted (MCA v2.1.0, API v3.0.0, Component
                          v3.1.5)
              MCA errmgr: default_tool (MCA v2.1.0, API v3.0.0, Component
                          v3.1.5)
              MCA errmgr: dvm (MCA v2.1.0, API v3.0.0, Component v3.1.5)
                 MCA ess: env (MCA v2.1.0, API v3.0.0, Component v3.1.5)
                 MCA ess: hnp (MCA v2.1.0, API v3.0.0, Component v3.1.5)
                 MCA ess: pmi (MCA v2.1.0, API v3.0.0, Component v3.1.5)
                 MCA ess: singleton (MCA v2.1.0, API v3.0.0, Component
                          v3.1.5)
                 MCA ess: tool (MCA v2.1.0, API v3.0.0, Component v3.1.5)
                 MCA ess: slurm (MCA v2.1.0, API v3.0.0, Component v3.1.5)
               MCA filem: raw (MCA v2.1.0, API v2.0.0, Component v3.1.5)
             MCA grpcomm: direct (MCA v2.1.0, API v3.0.0, Component v3.1.5)
                 MCA iof: hnp (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                 MCA iof: orted (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                 MCA iof: tool (MCA v2.1.0, API v2.0.0, Component v3.1.5)
            MCA notifier: syslog (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                MCA odls: default (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                 MCA oob: tcp (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                 MCA oob: ud (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                 MCA plm: isolated (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                 MCA plm: rsh (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                 MCA plm: slurm (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                 MCA ras: simulator (MCA v2.1.0, API v2.0.0, Component
                          v3.1.5)
                 MCA ras: slurm (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                MCA regx: fwd (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                MCA regx: naive (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                MCA regx: reverse (MCA v2.1.0, API v1.0.0, Component v3.1.5)
               MCA rmaps: mindist (MCA v2.1.0, API v2.0.0, Component v3.1.5)
               MCA rmaps: ppr (MCA v2.1.0, API v2.0.0, Component v3.1.5)
               MCA rmaps: rank_file (MCA v2.1.0, API v2.0.0, Component
                          v3.1.5)
               MCA rmaps: resilient (MCA v2.1.0, API v2.0.0, Component
                          v3.1.5)
               MCA rmaps: round_robin (MCA v2.1.0, API v2.0.0, Component
                          v3.1.5)
               MCA rmaps: seq (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                 MCA rml: oob (MCA v2.1.0, API v3.0.0, Component v3.1.5)
              MCA routed: binomial (MCA v2.1.0, API v3.0.0, Component v3.1.5)
              MCA routed: direct (MCA v2.1.0, API v3.0.0, Component v3.1.5)
              MCA routed: radix (MCA v2.1.0, API v3.0.0, Component v3.1.5)
                 MCA rtc: hwloc (MCA v2.1.0, API v1.0.0, Component v3.1.5)
              MCA schizo: flux (MCA v2.1.0, API v1.0.0, Component v3.1.5)
              MCA schizo: ompi (MCA v2.1.0, API v1.0.0, Component v3.1.5)
              MCA schizo: orte (MCA v2.1.0, API v1.0.0, Component v3.1.5)
              MCA schizo: slurm (MCA v2.1.0, API v1.0.0, Component v3.1.5)
               MCA state: app (MCA v2.1.0, API v1.0.0, Component v3.1.5)
               MCA state: dvm (MCA v2.1.0, API v1.0.0, Component v3.1.5)
               MCA state: hnp (MCA v2.1.0, API v1.0.0, Component v3.1.5)
               MCA state: novm (MCA v2.1.0, API v1.0.0, Component v3.1.5)
               MCA state: orted (MCA v2.1.0, API v1.0.0, Component v3.1.5)
               MCA state: tool (MCA v2.1.0, API v1.0.0, Component v3.1.5)
                 MCA bml: r2 (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                MCA coll: basic (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                MCA coll: inter (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                MCA coll: libnbc (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                MCA coll: self (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                MCA coll: sm (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                MCA coll: spacc (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                MCA coll: sync (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                MCA coll: tuned (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                MCA coll: cuda (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                MCA fbtl: posix (MCA v2.1.0, API v2.0.0, Component v3.1.5)
               MCA fcoll: dynamic (MCA v2.1.0, API v2.0.0, Component v3.1.5)
               MCA fcoll: dynamic_gen2 (MCA v2.1.0, API v2.0.0, Component
                          v3.1.5)
               MCA fcoll: individual (MCA v2.1.0, API v2.0.0, Component
                          v3.1.5)
               MCA fcoll: static (MCA v2.1.0, API v2.0.0, Component v3.1.5)
               MCA fcoll: two_phase (MCA v2.1.0, API v2.0.0, Component
                          v3.1.5)
                  MCA fs: ufs (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                  MCA io: ompio (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                  MCA io: romio314 (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                 MCA osc: sm (MCA v2.1.0, API v3.0.0, Component v3.1.5)
                 MCA osc: pt2pt (MCA v2.1.0, API v3.0.0, Component v3.1.5)
                 MCA osc: rdma (MCA v2.1.0, API v3.0.0, Component v3.1.5)
                 MCA pml: cm (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                 MCA pml: ob1 (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                 MCA pml: v (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                 MCA rte: orte (MCA v2.1.0, API v2.0.0, Component v3.1.5)
            MCA sharedfp: individual (MCA v2.1.0, API v2.0.0, Component
                          v3.1.5)
            MCA sharedfp: lockedfile (MCA v2.1.0, API v2.0.0, Component
                          v3.1.5)
            MCA sharedfp: sm (MCA v2.1.0, API v2.0.0, Component v3.1.5)
                MCA topo: basic (MCA v2.1.0, API v2.2.0, Component v3.1.5)
                MCA topo: treematch (MCA v2.1.0, API v2.2.0, Component
                          v3.1.5)
           MCA vprotocol: pessimist (MCA v2.1.0, API v2.0.0, Component
                          v3.1.5)
```

### PR DESCRIPTION
**Pull request by devreal**
The current implementation uses a void* to store different types of attribute value integers and attempts to figure out proper offsets for storing smaller integers in that pointer. The required pointer aliasing is UB and causes issues with GCC 11.

The new implementation replaces the self-built pointer-based union with a C union and selects the (pointer to the) right field based on the av_set_from value.

This patch also fixes a bug where copied attributes always had the set_from field set to C pointer, which worked but is technically not correct.

Supersedes #10343 
Fixes #10339 

Signed-off-by: Joseph Schuchart <schuchart@icl.utk.edu>

### CODE REVIEW

**Review by ggouaillardet — COMMENTED** [review]
Have you tested this on a big endian cpu with 8 bytes Fortran `INTEGER`?

I suspect that would not work when "converting" between (4 bytes) `int` and (8 bytes) `INTEGER`.

This is the reason I suggested we keep the `*_pos` logic but initialize at compile time based on pointer sizes and endianness.

**Comment by ggouaillardet** [comment]
FWIW, an quick (and likely thread safe) workaround is to declare
```
    void * volatile bogus = (void*) 1;
```
(and keep `bogus` and `p` as local variables)

**Comment by devreal** [comment]
> I suspect that would not work when "converting" between (4 bytes) int and (8 bytes) INTEGER.

I don't see where there would be an issue in this implementation. We would read the 4B int (`av_int`) and cast it to `MPI_Fint` (`translate_to_fint`) before passing it to the duplicate/delete callback (`COPY_ATTR_CALLBACKS`/`DELETE_ATTR_CALLBACKS`) or return it to the caller (`ompi_attr_get_fint`). Where would that fail? AFAICS, that is what the current implementation does, except that it crams everything into a `void*` and tries to be smart about the storage space. Obviously, GCC has become smarter, which is why we're spending hours on this. Really, that's what a C union is for.

>     void * volatile bogus = (void*) 1;

Sure, that's a bandaid that will work until it doesn't because some compiler will figure out that aliasing the storage of a `void*` as two int is still UB even though you slap `volatile` on it. Plus, I don't see the benefit of the current implementation over my proposal. 

Looking at the original code, I think the pointer arithmetic was broken too:

> `item->av_int_pointer = (int *)&item->av_value + int_pos;`

Taking the address of `item->av_value` (`void**`) and adding `int_pos` would point `av_int_pointer` past `av_value` in the structure in any case where `int_pos != 0`. Incidentally, with `int_pos == 1` it would point `av_int_pointer` to itself. I have no idea how that could have ever worked :man_shrugging:

**Comment by hjelmn** [comment]
I agree with @devreal . The existing code is not valid C and the compiler is now showing that. The correct fix is to use a union.

File: ompi/attribute/attribute.c [hunk 1]
```diff
@@ -393,25 +391,30 @@ do { \
  * Cases for attribute values
  */
 typedef enum ompi_attribute_translate_t {
+    OMPI_ATTRIBUTE_INVALID,
```
Comment (hjelmn) [inline ompi/attribute/attribute.c:394]: Doesn't this break internal ABI? Maybe do ```OMPI_ATTRIBUTE_INVALID = -1``` to avoid shifting the existing values by one.

File: ompi/attribute/attribute.c [hunk 2]
```diff
@@ -393,25 +391,30 @@ do { \
...
     OMPI_ATTRIBUTE_C,
     OMPI_ATTRIBUTE_INT,
     OMPI_ATTRIBUTE_FINT,
     OMPI_ATTRIBUTE_AINT
```
Comment (hjelmn) [inline ompi/attribute/attribute.c:398]: Minor nit. While you are editing this file can you add a trailing comma?

File: ompi/attribute/attribute.c [hunk 3]
```diff
@@ -1400,25 +1385,25 @@ static int get_value(opal_hash_table_t *attr_hash, int key,
...
 {
     switch (val->av_set_from) {
     case OMPI_ATTRIBUTE_C:
         /* Case 1: wrote a C pointer, read a C pointer
            (unity) */
-        return val->av_value;
+        return val->av_value.av_pointer;
 
     case OMPI_ATTRIBUTE_INT:
         /* Case 4: wrote an int, read a C pointer */
```
Comment (hjelmn) [inline ompi/attribute/attribute.c:1397]: Are these comments still correct? It is no longer a pointer, right?

Comment (hjelmn) [reply ompi/attribute/attribute.c:1397]: I guess it still is kinda right. It is returning a C pointer not reading one (at least at this point).

**Comment by dalcinl** [comment]
@devreal I reran mpi4py's testsuite against your clone and branch, but it is still failing. I though that the issue was related to attributes, as the original report came from using Win attributes, but looks like something else broke during the last week or so.

full log: https://github.com/mpi4py/mpi4py-testing/runs/6256108177?check_suite_focus=true

```
...
----------------------------------------------------------------------
Ran 1624 tests in 38.083s

OK (skipped=284)
python: win/win.c:463: ompi_win_destruct: Assertion `OPAL_OBJ_MAGIC_ID == ((opal_object_t *) (win->error_handler))->obj_magic_id' failed.
[fv-az173-499:164497] *** Process received signal ***
[fv-az173-499:164497] Signal: Aborted (6)
[fv-az173-499:164497] Signal code:  (-6)
[fv-az173-499:164497] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x430c0)[0x7f3e5bd890c0]
[fv-az173-499:164497] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f3e5bd8903b]
[fv-az173-499:164497] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f3e5bd68859]
[fv-az173-499:164497] [ 3] /lib/x86_64-linux-gnu/libc.so.6(+0x22729)[0x7f3e5bd68729]
[fv-az173-499:164497] [ 4] /lib/x86_64-linux-gnu/libc.so.6(+0x34006)[0x7f3e5bd7a006]
[fv-az173-499:164497] [ 5] /usr/local/lib/libmpi.so.0(+0xc0363)[0x7f3e5a389363]
[fv-az173-499:164497] [ 6] /usr/local/lib/libmpi.so.0(+0xbdfc6)[0x7f3e5a386fc6]
[fv-az173-499:164497] [ 7] /usr/local/lib/libmpi.so.0(+0xbe41e)[0x7f3e5a38741e]
[fv-az173-499:164497] [ 8] /usr/local/lib/libopen-pal.so.0(opal_finalize_cleanup_domain+0x42)[0x7f3e5a1bad8b]
[fv-az173-499:164497] [ 9] /usr/local/lib/libopen-pal.so.0(opal_finalize+0x5a)[0x7f3e5a1bb00e]
[fv-az173-499:164497] [10] /usr/local/lib/libmpi.so.0(ompi_rte_finalize+0x33f)[0x7f3e5a38666a]
[fv-az173-499:164497] [11] /usr/local/lib/libmpi.so.0(+0xc9c64)[0x7f3e5a392c64]
[fv-az173-499:164497] [12] /usr/local/lib/libmpi.so.0(ompi_mpi_instance_finalize+0x135)[0x7f3e5a392fdd]
[fv-az173-499:164497] [13] /usr/local/lib/libmpi.so.0(ompi_mpi_finalize+0x5f9)[0x7f3e5a37f41d]
[fv-az173-499:164497] [14] /usr/local/lib/libmpi.so.0(PMPI_Finalize+0x71)[0x7f3e5a3d2393]
[fv-az173-499:164497] [15] /opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/mpi4py/MPI.cpython-310-x86_64-linux-gnu.so(+0x3db36)[0x7f3e5a7bab36]
[fv-az173-499:164497] [16] /opt/hostedtoolcache/Python/3.10.4/x64/lib/libpython3.10.so.1.0(+0x104420)[0x7f3e5c04b420]
[fv-az173-499:164497] [17] /opt/hostedtoolcache/Python/3.10.4/x64/lib/libpython3.10.so.1.0(Py_Exit+0xc)[0x7f3e5c04b955]
[fv-az173-499:164497] [18] /opt/hostedtoolcache/Python/3.10.4/x64/lib/libpython3.10.so.1.0(+0x10710e)[0x7f3e5c04e10e]
[fv-az173-499:164497] [19] /opt/hostedtoolcache/Python/3.10.4/x64/lib/libpython3.10.so.1.0(PyErr_PrintEx+0x1d)[0x7f3e5c1c903d]
[fv-az173-499:164497] [20] /opt/hostedtoolcache/Python/3.10.4/x64/lib/libpython3.10.so.1.0(_PyRun_SimpleFileObject+0x3a0)[0x7f3e5c04de5f]
[fv-az173-499:164497] [21] /opt/hostedtoolcache/Python/3.10.4/x64/lib/libpython3.10.so.1.0(_PyRun_AnyFileObject+0x88)[0x7f3e5c04ef36]
[fv-az173-499:164497] [22] /opt/hostedtoolcache/Python/3.10.4/x64/lib/libpython3.10.so.1.0(Py_RunMain+0x3cf)[0x7f3e5c1d206f]
[fv-az173-499:164497] [23] /opt/hostedtoolcache/Python/3.10.4/x64/lib/libpython3.10.so.1.0(Py_BytesMain+0x3d)[0x7f3e5c1d1b1d]
[fv-az173-499:164497] [24] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f3e5bd6a0b3]
[fv-az173-499:164497] [25] python(_start+0x2e)[0x559e007d909e]
[fv-az173-499:164497] *** End of error message ***
--------------------------------------------------------------------------
prterun noticed that process rank 0 with PID 0 on node fv-az173-499 exited on signal 6 (Aborted).
--------------------------------------------------------------------------

Error: Process completed with exit code 134.
```

**Comment by devreal** [comment]
@dalcinl Thanks, I will look into it.

File: ompi/attribute/attribute.c (hunk 1 above)
Comment (bosilca) [reply ompi/attribute/attribute.c:394]: or move it at the end as OMPI_ATTRIBUTE_MAX_VALID.

File: ompi/attribute/attribute.c [hunk 4]
```diff
@@ -1468,37 +1453,131 @@ static MPI_Fint translate_to_fint(attribute_value_t *val)
...
+        val->av_value.av_aint = aint;
+
+    default:
+        /* Should never reach here */
+        return;
+    }
+}
+
+/*
+ * Set the attribute value from a given aint. Needed for the Fortran interface.
```
Comment (jsquyres) [inline ompi/attribute/attribute.c:1546]:
```suggestion
 * Set the attribute value from a given Fint. Needed for the Fortran interface.
```

File: ompi/attribute/attribute.c [hunk 5]
```diff
@@ -1468,37 +1453,131 @@ static MPI_Fint translate_to_fint(attribute_value_t *val)
...
+        return &val->av_value.av_aint;
+
+    default:
+        /* Should never reach here */
+        return NULL;
+    }
+}
+
+/*
+ * Set the attribute value from a given aint. Needed for the Fortran interface.
```
Comment (jsquyres) [inline ompi/attribute/attribute.c:1515]:
```suggestion
 * Set the attribute value from a given aint.
```

**Review by jsquyres — COMMENTED** [review]
Using a union is a much better approach.

**Comment by devreal** [comment]
I made a change to the `COPY_ATTR_CALLBACKS` macro and removed the `set_from_aint`/`set_from_fint` functions introduced earlier. This seems to be a corner case and I'm not 100% sure how to correctly handle it: assuming an attribute is created through either of the Fortran API and a value  for that attribute is set through the C API and assuming that this is actually legal (if not the remainder is moot and there is no problem; it likely opens the gates of hell if the MPI-1 Fortran API is used, due to truncation of the pointer value). The `av_set_from` field is set to `OMPI_ATTRIBUTE_C` when the value is set. Later, the atttribute is duplicated, which invokes the respective Fortran copy function, either copying the value as `MPI_Aint` or `MPI_Fint`. Thus, in the new attribute the value should be marked as `OMPI_ATTRIBUTE_AINT` or `OMPI_ATTRIBUTE_FINT`, even though it originated from C. It doesn't really matter for `OMPI_ATTRIBUTE_AINT` but certainly matters for `OMPI_ATTRIBUTE_FINT`. @jsquyres do you have an opinion on that? The original code (by accident) had always marked the value in the new attribute as `OMPI_ATTRIBUTE_C` because that was the value set in the constructor...

I will squash the changes I pushed once approved, just wanted an easy path to restore these functions if need be.

File: ompi/attribute/attribute.c (hunk 1 above)
Comment (devreal) [reply ompi/attribute/attribute.c]: There is no internal ABI, it's all in the same file. Changed it to -1 nevertheless.

**Comment by devreal** [comment]
@dalcinl I was unable to reproduce the crash with mpi4py. I tried running with valgrind and found some spurious invalid reads like the one below but nothing that could corrupt the magic ID and no double free.

```
==3190251== Invalid read of size 4
==3190251==    at 0x58E553: ??? (in /usr/bin/python3.8)
==3190251==    by 0x5C658B: _PyModule_ClearDict (in /usr/bin/python3.8)
==3190251==    by 0x68485D: PyImport_Cleanup (in /usr/bin/python3.8)
==3190251==    by 0x67F8AE: Py_FinalizeEx (in /usr/bin/python3.8)
==3190251==    by 0x6B70FC: Py_RunMain (in /usr/bin/python3.8)
==3190251==    by 0x6B736C: Py_BytesMain (in /usr/bin/python3.8)
==3190251==    by 0x488E0B2: (below main) (libc-start.c:308)
==3190251==  Address 0x4ea0020 is 912 bytes inside a block of size 992 free'd
==3190251==    at 0x483CA3F: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==3190251==    by 0x5F26424: opal_hash_table_destruct (in /home/joseph/opt/openmpi-master-dbg/lib/libopen-pal.so.0.0.0)
==3190251==    by 0x5F9F6A8: opal_obj_run_destructors (in /home/joseph/opt/openmpi-master-dbg/lib/libopen-pal.so.0.0.0)
==3190251==    by 0x5F9FDC1: infosubscriber_destruct (in /home/joseph/opt/openmpi-master-dbg/lib/libopen-pal.so.0.0.0)
==3190251==    by 0x5B21BB5: opal_obj_run_destructors (in /home/joseph/opt/openmpi-master-dbg/lib/libmpi.so.0.0.0)
==3190251==    by 0x5B238C5: ompi_win_free (in /home/joseph/opt/openmpi-master-dbg/lib/libmpi.so.0.0.0)
==3190251==    by 0x5BC33B9: PMPI_Win_free (in /home/joseph/opt/openmpi-master-dbg/lib/libmpi.so.0.0.0)
==3190251==    by 0x59257A4: __pyx_pf_6mpi4py_3MPI_3Win_22Free (MPI.c:159636)
==3190251==    by 0x59257A4: __pyx_pw_6mpi4py_3MPI_3Win_23Free (MPI.c:159606)
==3190251==    by 0x503B98: ??? (in /usr/bin/python3.8)
==3190251==    by 0x56B1D9: _PyEval_EvalFrameDefault (in /usr/bin/python3.8)
==3190251==    by 0x5F6835: _PyFunction_Vectorcall (in /usr/bin/python3.8)
==3190251==    by 0x56B1D9: _PyEval_EvalFrameDefault (in /usr/bin/python3.8)
==3190251==  Block was alloc'd at
==3190251==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==3190251==    by 0x5F264B6: opal_hash_table_init2 (in /home/joseph/opt/openmpi-master-dbg/lib/libopen-pal.so.0.0.0)
==3190251==    by 0x5F26575: opal_hash_table_init (in /home/joseph/opt/openmpi-master-dbg/lib/libopen-pal.so.0.0.0)
==3190251==    by 0x5F9FAD9: infosubscriber_construct (in /home/joseph/opt/openmpi-master-dbg/lib/libopen-pal.so.0.0.0)
==3190251==    by 0x5B21B3D: opal_obj_run_constructors (in /home/joseph/opt/openmpi-master-dbg/lib/libmpi.so.0.0.0)
==3190251==    by 0x5B21C75: opal_obj_new (in /home/joseph/opt/openmpi-master-dbg/lib/libmpi.so.0.0.0)
==3190251==    by 0x5B21AA9: opal_obj_new_debug (in /home/joseph/opt/openmpi-master-dbg/lib/libmpi.so.0.0.0)
==3190251==    by 0x5B2264B: alloc_window (in /home/joseph/opt/openmpi-master-dbg/lib/libmpi.so.0.0.0)
==3190251==    by 0x5B22EA7: ompi_win_allocate (in /home/joseph/opt/openmpi-master-dbg/lib/libmpi.so.0.0.0)
==3190251==    by 0x5BBF114: PMPI_Win_allocate (in /home/joseph/opt/openmpi-master-dbg/lib/libmpi.so.0.0.0)
==3190251==    by 0x5976C7C: PyMPI_Win_allocate_c (largecnt.h:1826)
==3190251==    by 0x5976C7C: __pyx_pf_6mpi4py_3MPI_3Win_10Allocate (MPI.c:158444)
==3190251==    by 0x5976C7C: __pyx_pw_6mpi4py_3MPI_3Win_11Allocate (MPI.c:158378)
==3190251==    by 0x5F3988: PyCFunction_Call (in /usr/bin/python3.8)

```

**Comment by dalcinl** [comment]
@devreal I found a trivial reproducer. I'm using the branch from this PR. However, at this point I'm not sure the issue is related to attributes.


```python
from mpi4py import MPI

for i in range(14):
    MPI.INFO_ENV.Dup().Free()
```

Iterating 14 times (or more) as in the snippet above triggers the assertion, but using 13 or less, all is good and valgrind is clean.

```
$ python tmp.py 
python: win/win.c:463: ompi_win_destruct: Assertion `OPAL_OBJ_MAGIC_ID == ((opal_object_t *) (win->error_handler))->obj_magic_id' failed.
[localhost:591040] *** Process received signal ***
[localhost:591040] Signal: Aborted (6)
[localhost:591040] Signal code:  (-6)
[localhost:591040] [ 0] /lib64/libc.so.6(+0x59da0)[0x7fbb32216da0]
...
[localhost:591040] [22] python(_start+0x25)[0x55a2b0cb5095]
[localhost:591040] *** End of error message ***
Aborted (core dumped)
```

**Comment by jsquyres** [comment]
@dalcinl Thanks for the reproducer.  That led @devreal to find the fix -- coming on a different PR (because it's unrelated to attributes).

**Review by jsquyres — COMMENTED** [review]
LGTM.  Let's squash.

**Comment by devreal** [comment]
Squashed, will merge once tests have passed.

**Comment by ggouaillardet** [comment]
IIRC things became tricky when Fortran sets a 8 bytes INTEGER and C reads
it, expecting an int*

On a big ending cpu, you'd have to return a pointer to the middle of the
Fortran INTEGER.

But this might be some old MPI1 only bozo cases that have been removed from
the standard.

**Comment by jeffhammond** [comment]
@ggouaillardet A large number of things - including all parameters of root and count - in MPI implementations break when users force Fortran `INTEGER` to be incompatible with C `int`.  No implementation I'm aware of supports this, and I'm not aware of any attempt to implement safe casting from 64b to 32b integers at the boundary between Fortran and C.

Nothing in the Fortran or MPI standard says this should work, and I don't think it's good for anyone for implementers to try.
