### PR TITLE
A big refresh of the datatype engine

### LINKED ISSUE #5540: Issue with overlapping vector datatype
As reported by the DKRZ folks, creating a datatype with overlapping capabilities (legal for all send communications) leads to data corruption, as the packing and unpacking function will fail to compute the correct memory layout.

A simple example of such datatype is:

```c
MPI_Type_vector(3, 1, 0, MPI_INT, &btypes[0]);
MPI_Type_indexed(1, (int[]){1}, (int[]){0}, MPI_INT, &btypes[1]);

MPI_Type_create_struct(2, (int[]){1,1}, (MPI_Aint[]){0,12}, btypes, &dt);
```
All Open MPI versions are affected. However, it has been decided during the weekly call to only fix it in every release after 3.0 and obviously master.

### PR DESCRIPTION
**Pull request by bosilca**
Faster and less error prone. this patch is a significant redesign of the internals of the datatype engine. No API or ABI changes.

Fixes #5540 (Issue with overlapping vector datatype)

### CODE REVIEW

**Comment by bosilca** [comment]
I put together the datatype related benchmarks we exchanged on the different datatype issues and PRs in a single repo (https://github.com/bosilca/ddt_bench).

File: opal/datatype/opal_datatype_memcpy.h [hunk 1]
```diff
@@ -14,7 +14,30 @@
...
+ * that is built with basic datatypes.
+ * Specifying a fixed size for the memcpy() makes the intel compiler
+ * inline it as an assignment operation.
+ * This code is a bit hacky, but doing this we can divide the latency
+ * by up to 2 during DDT exechanges.
+ */
+#define MEMCPY( DST, SRC, BLENGTH )                                 \
+    do {                                                            \
+        if( (BLENGTH) < 16 ) {                                      \
+            uintptr_t align = ((uintptr_t)(DST)) ^ ((uintptr_t)(SRC));                        \
```
Comment (derbeyn) [inline opal/datatype/opal_datatype_memcpy.h]: Are you really sure there will be a gain assigning instead of memcpy'ing, if both the src and dst are not aligned, even if it is the same misalignment?
Wondering whether we shouldn't replace the "^" by a "|"

File: opal/datatype/opal_datatype_memcpy.h [hunk 2]
```diff
@@ -11,10 +11,35 @@
...
+ */
+#define MEMCPY( DST, SRC, BLENGTH )                                      \
+    do {                                                                 \
+        if( (BLENGTH) < (size_t)opal_cache_line_size ) {                 \
+            uintptr_t align = ((uintptr_t)(DST)) | ((uintptr_t)(SRC));   \
+            TYPED_MEMCPY( (DST), (SRC), (BLENGTH), align, int32_t );     \
+            TYPED_MEMCPY( (DST), (SRC), (BLENGTH), align, int64_t );     \
+            TYPED_MEMCPY( (DST), (SRC), (BLENGTH), align, long double);  \
+        }                                                                \
+        memcpy((DST), (SRC), (BLENGTH));                                 \
```
Comment (derbeyn) [inline opal/datatype/opal_datatype_memcpy.h]: memcpy() should be called in an "else"

File: opal/datatype/opal_datatype_memcpy.h [hunk 3]
```diff
@@ -11,10 +11,35 @@
...
+#include "opal/runtime/opal.h"
+
 #ifndef OPAL_DATATYPE_MEMCPY_H_HAS_BEEN_INCLUDED
 #define OPAL_DATATYPE_MEMCPY_H_HAS_BEEN_INCLUDED
 
-#define MEMCPY( DST, SRC, BLENGTH ) \
-    memcpy( (DST), (SRC), (BLENGTH) )
+#define TYPED_MEMCPY( DST, SRC, BLENGTH, ALIGN, TYPE) \
+    if( ((BLENGTH) == sizeof(TYPE)) && (0 == ((ALIGN) & (sizeof(TYPE) - 1))) ) { \
+        for( size_t _i = 0; _i < ((BLENGTH) / sizeof(TYPE)); _i++ ) \
```
Comment (derbeyn) [inline opal/datatype/opal_datatype_memcpy.h]: why looping here?
since sizeof(TYPE) = BLENGTH, we are sure _i is always and only equal to 0.
Or may be I missed something?

File: opal/datatype/opal_datatype_memcpy.h (hunk 2 above)
Comment (derbeyn) [reply opal/datatype/opal_datatype_memcpy.h]: forget this comment: I missed the "break" above... sorry for that

File: opal/datatype/opal_datatype_module.c [hunk 4]
```diff
@@ -254,6 +254,7 @@ int32_t opal_datatype_init( void )
         datatype->desc.desc[0].elem.common.type  = i;
         /* datatype->desc.desc[0].elem.blocklen XXX not set at the moment, it will be needed later */
```
Comment (derbeyn) [inline opal/datatype/opal_datatype_module.c]: may be remove this comment?

File: opal/datatype/opal_datatype_unpack.h [hunk 5]
```diff
@@ -27,83 +27,116 @@
...
+        OPAL_DATATYPE_SAFEGUARD_POINTER( _memory, do_now_bytes, (CONVERTOR)->pBaseBuf,
                                         (CONVERTOR)->pDesc, (CONVERTOR)->count );
-            DO_DEBUG( opal_output( 0, "unpack 2. memcpy( %p, %p, %lu ) => space %lu\n",
-                                   (void*)_destination, (void*)*(SOURCE), (unsigned long)_copy_blength, (unsigned long)(*(SPACE) - (_i * _copy_blength)) ); );
-            MEMCPY_CSUM( _destination, *(SOURCE), _copy_blength, (CONVERTOR) );
-            *(SOURCE)    += _copy_blength;
-            _destination += _elem->extent;
-        }
-        _copy_blength *= _copy_count;
+        DO_DEBUG( opal_output( 0, "pack 3. memcpy( %p, %p, %lu ) => space %lu [epilog]\n",
```
Comment (derbeyn) [inline opal/datatype/opal_datatype_unpack.h]: s/pack/unpack/

File: opal/datatype/opal_datatype_unpack.h [hunk 6]
```diff
@@ -27,83 +27,116 @@
...
-        *(SOURCE)    += _copy_blength;
-        _destination += _copy_blength;
-    } else {
-        for(size_t _i = 0; _i < _copy_count; _i++ ) {
-            OPAL_DATATYPE_SAFEGUARD_POINTER( _destination, _copy_blength, (CONVERTOR)->pBaseBuf,
+    /* Do as many full blocklen as possible */
+    for(size_t _i = 0; _elem->blocklen <= cando_count; _i++ ) {
+        OPAL_DATATYPE_SAFEGUARD_POINTER( _memory, blocklen_bytes, (CONVERTOR)->pBaseBuf,
+                                         (CONVERTOR)->pDesc, (CONVERTOR)->count );
+        DO_DEBUG( opal_output( 0, "pack 2. memcpy( %p, %p, %lu ) => space %lu\n",
```
Comment (derbeyn) [inline opal/datatype/opal_datatype_unpack.h]: s/pack/unpack/

File: opal/datatype/opal_convertor.c [hunk 7]
```diff
@@ -578,8 +579,9 @@ int32_t opal_convertor_prepare_for_recv( opal_convertor_t* convertor,
     assert(! (convertor->flags & CONVERTOR_SEND));
     OPAL_CONVERTOR_PREPARE( convertor, datatype, count, pUserBuf );
 
-    if( convertor->flags & CONVERTOR_WITH_CHECKSUM ) {
-        if( !(convertor->flags & CONVERTOR_HOMOGENEOUS) ) {
+#if defined(CHECKSUM)
```
Comment (derbeyn) [inline opal/datatype/opal_convertor.c]: why didn't you do the same in opal_convertor_prepare_for_send()?

File: opal/datatype/opal_datatype_memcpy.h (hunk 3 above)
Comment (bosilca) [reply opal/datatype/opal_datatype_memcpy.h]: My final goal was to have some kind of Duff's device going from the largest to the smallest predefined type. I will update the code.

File: opal/datatype/opal_convertor.c (hunk 7 above)
Comment (bosilca) [reply opal/datatype/opal_convertor.c]: Thanks for noticing. I applied the same logic to the opal_convertor_prepare_for_send.

**Comment by hppritcha** [comment]
bot:ompi:retest

File: opal/datatype/opal_datatype_copy.h [hunk 8]
```diff
@@ -48,37 +48,37 @@ static inline void _predefined_data( const dt_elem_desc_t* ELEM,
...
+                                            (DATATYPE), (TOTAL_COUNT) );
+            DO_DEBUG( opal_output( 0, "copy %s( %p, %p, %" PRIsize_t " ) => space %" PRIsize_t "\n",
+                                   STRINGIFY(MEM_OP_NAME), (void*)_destination, (void*)_source, do_now_bytes, *(SPACE) ); );
+            MEM_OP( _destination, _source, do_now_bytes );
             _destination += _elem->extent;
+            _source      += _elem->extent;
+            *(SPACE)     -= do_now_bytes;
         }
-        _copy_blength *= _copy_count;
+        (COUNT)      -= total_count;
```
Comment (derbeyn) [inline opal/datatype/opal_datatype_copy.h]: I do not understand why you are decrementing COUNT here?
It has no effect, neither on the calling routine (since it is passed by value), neither in this one, since we are leaving right after.

File: opal/datatype/opal_datatype_position.c [hunk 9]
```diff
@@ -61,22 +61,77 @@ position_predefined_data( opal_convertor_t* CONVERTOR,
...
+        if( 0 != do_now ) {
+            size_t left_in_block = _elem->blocklen - do_now;  /* left in the current blocklen */
+            do_now = (left_in_block > cando_count ) ? cando_count : left_in_block;
+            do_now_bytes = do_now * opal_datatype_basicDatatypes[_elem->common.type]->size;
+
+            OPAL_DATATYPE_SAFEGUARD_POINTER( _memory, do_now_bytes, (CONVERTOR)->pBaseBuf,
+                                            (CONVERTOR)->pDesc, (CONVERTOR)->count );
+            DO_DEBUG( opal_output( 0, "position( %p, %lu ) => space %lu [prolog]\n",
+                                   (void*)_memory, (unsigned long)do_now_bytes, (unsigned long)(*(SPACE)) ); );
+            _memory      = *(POINTER) + _elem->disp + (ptrdiff_t)do_now_bytes;
```
Comment (derbeyn) [inline opal/datatype/opal_datatype_position.c]: _memory += (ptrdiff_t)do_now_bytes
(_memory has already been initialized at the very beginning)

File: opal/datatype/opal_datatype_position.c [hunk 10]
```diff
@@ -61,22 +61,77 @@ position_predefined_data( opal_convertor_t* CONVERTOR,
...
+    do_now = cando_count;
+    if( 0 != do_now ) {
+        do_now_bytes = do_now * opal_datatype_basicDatatypes[_elem->common.type]->size;
+        OPAL_DATATYPE_SAFEGUARD_POINTER( _memory, do_now_bytes, (CONVERTOR)->pBaseBuf,
+                                        (CONVERTOR)->pDesc, (CONVERTOR)->count );
+        DO_DEBUG( opal_output( 0, "position( %p, %lu ) => space %lu [epilog]\n",
+                               (void*)_memory, (unsigned long)do_now_bytes, (unsigned long)(*(SPACE)) ); );
+        _memory   += do_now_bytes;
+        *(SPACE)  -= do_now_bytes;
+        *(COUNT)  -= do_now;
```
Comment (derbeyn) [inline opal/datatype/opal_datatype_position.c]: Why not defining the following routine:
`static inline void process_single_block(opal_convertor_t *CONVERTOR,
                                        unsigned char *mem, ptrdiff_t mem_update,
                                        size_t *space, size_t space_update,
                                        size_t *cnt, size_t cnt_update,
                                        size_t do_now_bytes)
{
    OPAL_DATATYPE_SAFEGUARD_POINTER( mem, do_now_bytes, (CONVERTOR)->pBaseBuf,
                                    (CONVERTOR)->pDesc, (CONVERTOR)->count );
    DO_DEBUG( opal_output( 0, "position( %p, %lu ) => space %lu\n",
                           (void*)mem, (unsigned long)do_now_bytes, (unsigned long)*space ); );
    mem     += mem_update;
    *space  -= space_update;
    *cnt    -= cnt_update;
}
`

In the first check, you could call it as follows:
`process_single_block(CONVERTOR, _memory, (ptrdiff_t)do_now_bytes,
                                 SPACE, do_now_bytes, COUNT, do_now, do_now_bytes);`

In the full blocks processing, you could call it as follows:
` process_single_block(CONVERTOR, _memory, _elem->extent, SPACE, do_now_bytes, COUNT, _elem->blocklen, do_now_bytes);`

In the epilog, you could call it as follows:
`process_single_block(CONVERTOR, _memory, (ptrdiff_t)do_now_bytes, SPACE, do_now_bytes, COUNT, do_now, do_now_bytes);`

File: opal/datatype/opal_datatype_pack.c [hunk 11]
```diff
@@ -111,155 +108,123 @@ opal_pack_homogeneous_contig_with_gaps_function( opal_convertor_t* pConv,
...
     assert( (pData->flags & OPAL_DATATYPE_FLAG_CONTIGUOUS) && ((ptrdiff_t)pData->size != extent) );
     DO_DEBUG( opal_output( 0, "pack_homogeneous_contig( pBaseBuf %p, iov_count %d )\n",
                            (void*)pConv->pBaseBuf, *out_size ); );
     if( stack[1].type != opal_datatype_uint1.id ) {
         stack[1].count *= opal_datatype_basicDatatypes[stack[1].type]->size;
         stack[1].type = opal_datatype_uint1.id;
     }
+    /* We can provide directly the pointers in the user buffers (like the convertor_raw) */
+    if( NULL == iov[0].iov_base ) {
+        user_memory = pConv->pBaseBuf + pData->true_lb + stack[0].disp + stack[1].disp;
```
Comment (derbeyn) [inline opal/datatype/opal_datatype_pack.c]: why not 
- moving this line between the if {} and the for {} (after line # 144)
- removing line 142

File: opal/datatype/opal_datatype_copy.h (hunk 8 above)
Comment (bosilca) [reply opal/datatype/opal_datatype_copy.h]: for symmetry with the other functions, but you are right it is unnecessary.

File: opal/datatype/opal_datatype_pack.c (hunk 11 above)
Comment (bosilca) [reply opal/datatype/opal_datatype_pack.c]: It seems possible to rewrite this code without the ```if``` but I am not sure if it is really improves the readability or performance. Let me give it a try.

File: opal/datatype/opal_datatype_pack.c [hunk 12]
```diff
@@ -111,155 +108,118 @@ opal_pack_homogeneous_contig_with_gaps_function( opal_convertor_t* pConv,
...
+            user_memory += extent;
+            pConv->bConverted += stack[1].count;
+
+            stack[0].disp += extent;
+            stack[0].count--;
+            stack[1].disp = 0;
+            stack[1].count = pData->size;  /* we might need this to update the partial
+                                            * length for the first iteration */
+
+            user_memory = pConv->pBaseBuf + pData->true_lb + stack[0].disp;
```
Comment (derbeyn) [inline opal/datatype/opal_datatype_pack.c]: ... or this one

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b5fb4ca2df8a099dc9a5a16cf7890c32

File: opal/datatype/opal_datatype_memcpy.h [hunk 13]
```diff
@@ -11,10 +11,45 @@
...
-#define MEMCPY( DST, SRC, BLENGTH ) \
-    memcpy( (DST), (SRC), (BLENGTH) )
+#define TYPED_MEMCPY( DST, SRC, BLENGTH, ALIGN, TYPE)                   \
+    if( ((BLENGTH) >= sizeof(TYPE)) && (0 == ((ALIGN) & (sizeof(TYPE) - 1))) ) { \
+        TYPE *__dst = (TYPE*)(DST), *__src = (TYPE*)(SRC);              \
+        if( (BLENGTH) == sizeof(TYPE) ) {                               \
+            *__dst = *__src;                                            \
+            break;                                                      \
+        }                                                               \
+        size_t _cnt = ((BLENGTH) / sizeof(TYPE));                       \
```
Comment (derbeyn) [inline opal/datatype/opal_datatype_memcpy.h]: Is it really worth doing all this instead of a memcpy() if blength > sizeof(type)?
I'll do some measurements...

**Comment by jsquyres** [comment]
bot:ompi:retest

**Comment by jsquyres** [comment]
As noted on the 2019-06-25 webex, this PR is both a performance enhancement for the DDT engine, but it's also a fix for #5540 (i.e., an issue that has been observed on the v4.0.x branch).

**Comment by hppritcha** [comment]
@derbeyn could you sign off your review?  By that I mean click approve for the overall review.  Thanks.

**Comment by hppritcha** [comment]
@ggouaillardet could you review this PR when you have time?

**Comment by gpaulsen** [comment]
Looks like both `opal_datatype_test` and `ddt_test` Aborted at runtime in Mellanox CI (http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/10139).  This may be a real error, or perhaps the test case needs to be updated.

**Comment by jsquyres** [comment]
Copying the failed results here, because CI logs get recycled every so often:

```
...
07:45:45 PASS: unpack_hetero
07:45:45 PASS: position
07:45:45 PASS: checksum
07:45:45 PASS: position_noncontig
07:45:45 PASS: unpack_ooo
07:45:45 PASS: ddt_raw2
07:45:45 ../../config/test-driver: line 107:  6960 Aborted                 "$@" > $log_file 2>&1
07:45:45 FAIL: opal_datatype_test
07:45:45 PASS: external32
07:45:45 PASS: ddt_pack
07:45:45 PASS: large_data
07:45:45 ../../config/test-driver: line 107:  6978 Aborted                 "$@" > $log_file 2>&1
07:45:45 FAIL: ddt_test
07:45:45 PASS: ddt_raw
```

**Comment by gpaulsen** [comment]
@bosilca,

  @hppritcha and I were discussing this PR.  Would you mind PRing this back to v4.0.x (if you agree it's appropriate for v4.0.2) to resolve Issue https://github.com/open-mpi/ompi/issues/5540

**Comment by bosilca** [comment]
@hppritcha and @gpaulsen here is the 4.0 PR #6863.
